-- =============================================================================
-- CONFORMIA — 0004 : durcissement de l'authentification
--
-- Tout ce qui touche à la connexion s'exécute AVANT qu'une session n'existe :
-- l'appelant est `anon`. Les fonctions de ce fichier sont donc SECURITY DEFINER
-- et exposées à `anon` — chacune ne fait qu'une chose, et ne rend jamais
-- d'information permettant de deviner si un compte existe.
-- =============================================================================

-- =============================================================================
-- 1. TENTATIVES D'AUTHENTIFICATION
-- =============================================================================

create table public.auth_attempts (
  id bigint generated by default as identity primary key,
  email extensions.citext not null,
  ip_address inet,
  user_agent text,
  succeeded boolean not null default false,
  attempted_at timestamptz not null default now()
);

comment on table public.auth_attempts is
  'Tentatives de connexion, réussies ou non. Sert exclusivement à la limitation de '
  'débit. Purgée automatiquement au-delà de 24 h : ce n''est pas un journal d''audit — '
  'la trace durable d''un échec est LOGIN_FAILED dans audit_log.';
comment on column public.auth_attempts.email is
  'Adresse SAISIE, pas nécessairement celle d''un compte existant. Une adresse inconnue '
  'est comptabilisée comme les autres : sans cela, la limitation elle-même révélerait '
  'quels comptes existent.';

-- Les deux compteurs de la règle « 5 tentatives par e-mail ET par IP / 15 min ».
create index auth_attempts_email_idx on public.auth_attempts (email, attempted_at desc)
  where not succeeded;
create index auth_attempts_ip_idx on public.auth_attempts (ip_address, attempted_at desc)
  where not succeeded;
create index auth_attempts_purge_idx on public.auth_attempts (attempted_at);

alter table public.auth_attempts enable row level security;

create policy auth_attempts_select on public.auth_attempts
  for select to authenticated
  using (public.is_active_user() and public.has_permission('audit.read'));
comment on policy auth_attempts_select on public.auth_attempts is
  'Lecture réservée à audit.read : la liste des adresses tentées est en soi une '
  'information sensible. Aucune politique d''écriture — tout passe par '
  'record_auth_attempt(), qui est la seule porte.';

revoke insert, update, delete on public.auth_attempts from public, anon, authenticated, service_role;
grant select on public.auth_attempts to authenticated;

-- =============================================================================
-- 2. JOURNALISATION DES ÉVÉNEMENTS D'AUTHENTIFICATION
--    audit_trigger() ne couvre que les écritures de tables. Une connexion
--    refusée ne modifie aucune ligne : elle a donc besoin de sa propre porte.
-- =============================================================================

create or replace function public.log_auth_event(
  p_action text,
  p_email text,
  p_ip inet default null,
  p_user_agent text default null,
  p_actor_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_action not in ('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'MFA_RESET') then
    raise exception 'Événement d''authentification inconnu : %.', p_action
      using errcode = '22023';
  end if;

  insert into public.audit_log (
    actor_id, actor_email, action, entity_table, entity_id_ref,
    before, after, ip_address, user_agent
  )
  values (
    p_actor_id,
    -- L'adresse saisie est conservée telle quelle : sur un échec, c'est la seule
    -- information exploitable. Le MOT DE PASSE n'est jamais transmis à cette
    -- fonction, et n'a donc aucun moyen d'atteindre le journal.
    lower(btrim(p_email)),
    p_action,
    'auth',
    p_actor_id::text,
    null,
    null,
    p_ip,
    p_user_agent
  );
end;
$$;

comment on function public.log_auth_event(text, text, inet, text, uuid) is
  'Trace une connexion, un échec ou une déconnexion dans audit_log. Aucun paramètre '
  'ne porte de secret : la fonction ne peut structurellement pas journaliser un mot '
  'de passe.';

grant execute on function public.log_auth_event(text, text, inet, text, uuid) to anon, authenticated;

-- =============================================================================
-- 3. LIMITATION DE DÉBIT
-- =============================================================================

create or replace function public.record_auth_attempt(
  p_email text,
  p_ip inet default null,
  p_succeeded boolean default false,
  p_user_agent text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.auth_attempts (email, ip_address, user_agent, succeeded)
  values (lower(btrim(p_email)), p_ip, p_user_agent, p_succeeded);
end;
$$;

comment on function public.record_auth_attempt(text, inet, boolean, text) is
  'Enregistre une tentative. Appelée par `anon`, avant toute session.';

create or replace function public.is_auth_throttled(p_email text, p_ip inet default null)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  window_start timestamptz := now() - interval '15 minutes';
  max_attempts constant int := 5;
  by_email int;
  by_ip int;
begin
  select count(*) into by_email
  from public.auth_attempts a
  where a.email = lower(btrim(p_email))
    and not a.succeeded
    and a.attempted_at > window_start;

  if by_email >= max_attempts then
    return true;
  end if;

  if p_ip is null then
    return false;
  end if;

  select count(*) into by_ip
  from public.auth_attempts a
  where a.ip_address = p_ip
    and not a.succeeded
    and a.attempted_at > window_start;

  return by_ip >= max_attempts;
end;
$$;

comment on function public.is_auth_throttled(text, inet) is
  'Vrai au-delà de 5 échecs sur 15 minutes, par adresse e-mail OU par IP. '
  'La 6ᵉ tentative est donc refusée. Ne rend qu''un booléen : ni compteur, ni délai '
  'restant, ni indication de l''existence du compte.';

grant execute on function public.record_auth_attempt(text, inet, boolean, text) to anon, authenticated;
grant execute on function public.is_auth_throttled(text, inet) to anon, authenticated;

-- Purge : la table est un compteur glissant, pas une archive.
create or replace function public.purge_auth_attempts()
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.auth_attempts where attempted_at < now() - interval '24 hours';
$$;

comment on function public.purge_auth_attempts() is
  'Supprime les tentatives de plus de 24 h. Sans effet sur audit_log, qui conserve '
  'les LOGIN_FAILED pour la durée de rétention réglementaire.';

do $$
begin
  perform cron.unschedule('conformia-purge-auth-attempts')
  where exists (select 1 from cron.job where jobname = 'conformia-purge-auth-attempts');
  perform cron.schedule(
    'conformia-purge-auth-attempts', '17 * * * *',
    $job$select public.purge_auth_attempts()$job$
  );
exception when others then
  raise notice 'pg_cron indisponible (%) : planifier purge_auth_attempts() autrement.', sqlerrm;
end;
$$;

-- =============================================================================
-- 4. ÉTAT MFA
--    L'autorité est auth.mfa_factors, pas une colonne applicative : un facteur
--    supprimé côté Supabase doit invalider l'enrôlement sans intervention.
-- =============================================================================

create or replace function public.has_verified_mfa(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from auth.mfa_factors f
    where f.user_id = p_user_id and f.status = 'verified'
  );
$$;

comment on function public.has_verified_mfa(uuid) is
  'Second facteur réellement enrôlé et vérifié. Lit auth.mfa_factors : profiles.mfa_enrolled '
  'n''est qu''un reflet de confort, cette fonction fait foi.';

grant execute on function public.has_verified_mfa(uuid) to authenticated;

create or replace function public.mfa_required_for(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    public.setting_bool('require_mfa_all_users', false)
    or exists (
      select 1
      from public.user_roles ur
      join public.roles r on r.id = ur.role_id
      where ur.user_id = p_user_id
        and r.code in ('ADMIN', 'DIRECTION')
        and ur.revoked_at is null
        and (ur.expires_at is null or ur.expires_at > now())
    );
$$;

comment on function public.mfa_required_for(uuid) is
  'Le second facteur est EXIGÉ pour ADMIN et DIRECTION — les rôles qui administrent les '
  'droits ou valident. Pour les autres, il est proposé sans blocage. Le réglage '
  'require_mfa_all_users permet de généraliser l''exigence sans développement.';

grant execute on function public.mfa_required_for(uuid) to authenticated;

-- =============================================================================
-- 5. LISTE BLANCHE D'IP — RÔLE ADMIN UNIQUEMENT
-- =============================================================================

create or replace function public.is_ip_allowed_for_admin(p_ip inet)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  allowlist jsonb;
  entry text;
begin
  select s.value into allowlist from public.app_settings s where s.key = 'admin_ip_allowlist';

  -- Vide = aucune restriction. C'est le défaut : une liste blanche mal renseignée
  -- ne doit pas verrouiller l'administration hors de son propre outil.
  if allowlist is null or jsonb_array_length(allowlist) = 0 then
    return true;
  end if;

  if p_ip is null then
    return false;
  end if;

  for entry in select jsonb_array_elements_text(allowlist) loop
    begin
      if p_ip << entry::inet or p_ip = entry::inet then
        return true;
      end if;
    exception when others then
      -- Entrée illisible : ignorée plutôt que fatale, mais jamais permissive.
      continue;
    end;
  end loop;

  return false;
end;
$$;

comment on function public.is_ip_allowed_for_admin(inet) is
  'Restriction d''origine applicable au SEUL rôle ADMIN. Accepte adresses et préfixes '
  'CIDR. Liste vide = aucune restriction.';

grant execute on function public.is_ip_allowed_for_admin(inet) to authenticated;

-- =============================================================================
-- 5 bis. VERDICTS DE SESSION — un seul aller-retour depuis le middleware
--
--   Le middleware s'exécute à CHAQUE requête. Trois RPC séparés y coûteraient
--   trois allers-retours par navigation ; cette fonction les réunit.
-- =============================================================================

create or replace function public.session_gates(p_ip inet default null)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'authenticated', auth.uid() is not null,
    'active', public.is_active_user(),
    'is_admin', public.is_admin(),
    'mfa_required', coalesce(public.mfa_required_for(auth.uid()), false),
    'mfa_enrolled', coalesce(public.has_verified_mfa(auth.uid()), false),
    'ip_allowed', public.is_ip_allowed_for_admin(p_ip)
  );
$$;

comment on function public.session_gates(inet) is
  'Verdicts d''accès de la requête courante, en un seul appel : session active, '
  'appartenance à ADMIN, exigence et présence du second facteur, autorisation d''origine. '
  'Ne rend aucune donnée métier — le middleware n''a pas à en connaître.';

grant execute on function public.session_gates(inet) to authenticated;

-- =============================================================================
-- 6. DÉSACTIVATION D'UN COMPTE
--    Un compte n'est jamais supprimé : il devient inactif. Son nom continue
--    d'apparaître dans les traces, sinon l'audit deviendrait illisible.
-- =============================================================================

create or replace function public.open_occurrence_count(p_user_id uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $$
  select count(*)::int
  from public.obligation_occurrences oc
  where (oc.owner_id = p_user_id or oc.validator_id = p_user_id)
    and oc.deleted_at is null
    and oc.status not in ('ARCHIVED', 'NOT_APPLICABLE', 'SUBMITTED');
$$;

comment on function public.open_occurrence_count(uuid) is
  'Occurrences encore vivantes portées par un utilisateur, comme responsable ou '
  'comme validateur. Une désactivation ne peut pas laisser un dossier sans titulaire.';

grant execute on function public.open_occurrence_count(uuid) to authenticated;

create or replace function public.prevent_orphan_deactivation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  still_open int;
begin
  -- Ne vise que la bascule actif → inactif.
  if old.is_active and not new.is_active then
    still_open := public.open_occurrence_count(new.id);
    if still_open > 0 then
      raise exception
        'Désactivation refusée : % occurrence(s) ouverte(s) restent affectées à ce compte.',
        still_open
        using errcode = '23514',
              hint = 'Réaffecter ces occurrences à un autre responsable avant de désactiver.';
    end if;
  end if;
  return new;
end;
$$;

comment on function public.prevent_orphan_deactivation() is
  'Interdit de désactiver un compte portant des occurrences ouvertes. La règle est '
  'en base et non dans l''écran : une désactivation faite par script ou par API doit '
  'buter sur la même barrière. L''historique et les pièces déposées sont intégralement '
  'conservés — seul l''accès cesse.';

create trigger trg_profiles_prevent_orphan_deactivation
  before update on public.profiles
  for each row execute function public.prevent_orphan_deactivation();
