-- =============================================================================
-- 0010 — CIRCUIT DE VALIDATION
--
-- Cinq apports, et pas un de plus :
--
--   1. UNE SEULE FONCTION DÉCIDE. `evaluate_transition()` répond « cette
--      transition est-elle possible, et sinon pourquoi ». Elle est appelée par
--      `apply_occurrence_transition()` — donc par toute écriture — ET par le
--      service TypeScript qui grise les boutons. Il n'existe désormais aucune
--      règle de transition écrite deux fois : ni entre SQL et TypeScript, ni
--      entre l'interface et la base.
--
--   2. DOUBLE NIVEAU DE VALIDATION. Quand `obligation_types.validation_levels`
--      vaut 2, la première validation ne change PAS l'état : elle inscrit une
--      étape dans `occurrence_transitions`. Le dossier reste en attente jusqu'à
--      ce que la DIRECTION valide à son tour. La règle est portée par le
--      TRIGGER, pas seulement par la fonction d'application — sinon un UPDATE
--      direct par un détenteur de `occurrence.write` la contournerait.
--
--   3. IMMUABILITÉ D'UNE PÉRIODE ARCHIVÉE. Le verrou de 0001 protégeait la ligne
--      d'occurrence. Il ne protégeait NI les commentaires, NI la liste de
--      contrôle : on pouvait commenter et cocher un dossier archivé. Corrigé.
--
--   4. EFFETS DE BORD DÉCLARÉS EN TABLE. Qui est prévenu, à quelle transition,
--      avec ou sans motif : des lignes, pas des `if`. Ajouter une notification
--      ne demande aucun déploiement.
--
--   5. NOTIFICATIONS. La table manquait. Elle est écrite dans la MÊME
--      TRANSACTION que la transition : une transition sans sa notification n'est
--      pas un demi-succès, c'est un échec.
-- =============================================================================

-- =============================================================================
-- 1. IMMUABILITÉ D'UNE PÉRIODE ARCHIVÉE
-- =============================================================================

create or replace function public.enforce_parent_occurrence_lock()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  target_occurrence uuid;
  locked boolean;
begin
  target_occurrence := coalesce(
    (to_jsonb(new) ->> 'occurrence_id')::uuid,
    (to_jsonb(old) ->> 'occurrence_id')::uuid);

  if target_occurrence is null then
    return new;
  end if;

  select oc.is_locked into locked
  from public.obligation_occurrences oc
  where oc.id = target_occurrence;

  if coalesce(locked, false) then
    raise exception
      'Dossier archivé (id=%) : aucune modification de % acceptée.', target_occurrence, tg_table_name
      using errcode = '23514',
            hint = 'Rouvrir le dossier par la transition ARCHIVED → SUBMITTED (permission occurrence.unlock).';
  end if;

  return new;
end;
$fn$;

comment on function public.enforce_parent_occurrence_lock() is
  '⚠️ COMBLE UNE LACUNE de 0001. `enforce_occurrence_lock` protégeait la LIGNE '
  'd''occurrence — son statut, ses dates — mais rien de ce qui pend à elle. Un '
  'dossier archivé acceptait donc encore un commentaire et une coche de liste de '
  'contrôle : l''archive n''était pas fidèle à ce qui avait été déposé. '
  'Générique par construction (TG_TABLE_NAME, to_jsonb) : brancher une nouvelle '
  'table fille sur ce trigger suffit, aucune branche par nom de table à maintenir.';

create trigger trg_parent_lock
  before insert or update on public.occurrence_comments
  for each row execute function public.enforce_parent_occurrence_lock();

create trigger trg_parent_lock
  before insert or update on public.occurrence_checklist_items
  for each row execute function public.enforce_parent_occurrence_lock();

create trigger trg_parent_lock
  before insert or update on public.documents
  for each row execute function public.enforce_parent_occurrence_lock();

-- =============================================================================
-- 2. NOTIFICATIONS
-- =============================================================================

create table public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles (id) on delete restrict,
  kind text not null check (kind in (
    'VALIDATION_REQUESTED', 'OCCURRENCE_REJECTED', 'OCCURRENCE_UNLOCKED')),
  occurrence_id uuid references public.obligation_occurrences (id) on delete restrict,
  actor_id uuid references public.profiles (id) on delete restrict,
  reason text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

comment on table public.notifications is
  'Messages internes adressés à une personne. Écrits DANS LA MÊME TRANSACTION que '
  'la transition qui les provoque : une transition dont la notification échoue est '
  'annulée. Prévenir « au mieux » reviendrait à ne pas prévenir — le destinataire '
  'ne peut pas savoir qu''un message a été perdu. '
  '⚠️ Aucun canal SORTANT ici : ni courriel, ni message externe. Cette table est '
  'ce qu''un tel canal devra lire le jour où il existera.';
comment on column public.notifications.reason is
  'Motif repris de la transition, quand l''effet déclaré le demande — un rejet sans '
  'son motif oblige le destinataire à retourner le chercher.';

create index notifications_recipient_idx
  on public.notifications (recipient_id, created_at desc);
-- File « non lues » : le seul index réellement chaud, la navigation la compte.
create index notifications_unread_idx
  on public.notifications (recipient_id) where read_at is null;

alter table public.notifications enable row level security;

revoke insert, delete on public.notifications from public, anon, authenticated, service_role;
grant select, update on public.notifications to authenticated;

create policy notifications_select on public.notifications
  for select to authenticated
  using (public.is_active_user() and recipient_id = public.current_profile_id());
comment on policy notifications_select on public.notifications is
  'On ne lit que ses propres messages. Aucune exception, pas même pour l''audit : '
  'le journal d''audit dit déjà ce qui s''est passé, sans lire le courrier d''autrui.';

create policy notifications_update on public.notifications
  for update to authenticated
  using (public.is_active_user() and recipient_id = public.current_profile_id())
  with check (recipient_id = public.current_profile_id());
comment on policy notifications_update on public.notifications is
  'Marquer comme lu. Le contenu, lui, est immuable — voir le trigger.';

create or replace function public.enforce_notification_immutable()
returns trigger
language plpgsql
set search_path = ''
as $fn$
begin
  if new.recipient_id is distinct from old.recipient_id
     or new.kind is distinct from old.kind
     or new.occurrence_id is distinct from old.occurrence_id
     or new.actor_id is distinct from old.actor_id
     or new.reason is distinct from old.reason
     or new.created_at is distinct from old.created_at
  then
    raise exception 'Seule la date de lecture est modifiable sur une notification.'
      using errcode = '42501';
  end if;
  return new;
end;
$fn$;

create trigger trg_notification_immutable
  before update on public.notifications
  for each row execute function public.enforce_notification_immutable();

-- =============================================================================
-- 3. EFFETS DE BORD, DÉCLARÉS EN TABLE
-- =============================================================================

create table public.transition_notifications (
  id uuid primary key default gen_random_uuid(),
  from_status public.occurrence_status not null,
  to_status public.occurrence_status not null,
  recipient text not null check (recipient in ('VALIDATOR', 'OWNER', 'DIRECTION')),
  kind text not null,
  include_reason boolean not null default false,
  constraint transition_notifications_key unique (from_status, to_status, recipient)
);

comment on table public.transition_notifications is
  'Qui est prévenu, à quelle transition, avec ou sans le motif. DES DONNÉES, pas '
  'des `if` dispersés : ajouter un destinataire à une transition est une ligne, '
  'pas un déploiement (CLAUDE.md §3.5). Le verrouillage, lui, n''est PAS ici — il '
  'est déjà déclaré par status_transition_rules.locks_occurrence, et le répéter '
  'créerait deux sources pour une même décision.';

insert into public.transition_notifications
  (from_status, to_status, recipient, kind, include_reason)
values
  -- Soumission : le validateur doit savoir qu'on l'attend.
  ('IN_PROGRESS',        'PENDING_VALIDATION', 'VALIDATOR',  'VALIDATION_REQUESTED', false),
  -- Rejet : le préparateur doit recevoir le MOTIF, pas seulement le refus.
  ('PENDING_VALIDATION', 'REJECTED',           'OWNER',      'OCCURRENCE_REJECTED',  true),
  -- Réouverture d'archive : la Direction et le responsable, tous deux, avec le motif.
  ('ARCHIVED',           'SUBMITTED',          'DIRECTION',  'OCCURRENCE_UNLOCKED',  true),
  ('ARCHIVED',           'SUBMITTED',          'OWNER',      'OCCURRENCE_UNLOCKED',  true);

grant select on public.transition_notifications to authenticated;
alter table public.transition_notifications enable row level security;

create policy transition_notifications_select on public.transition_notifications
  for select to authenticated using (public.is_active_user());
comment on policy transition_notifications_select on public.transition_notifications is
  'Référentiel d''effets, lisible de tous : il ne contient aucune donnée métier.';

-- -----------------------------------------------------------------------------
-- Application des effets — dans la transaction de la transition
-- -----------------------------------------------------------------------------

create or replace function public.dispatch_transition_notifications(
  p_occurrence public.obligation_occurrences,
  p_from public.occurrence_status,
  p_to public.occurrence_status,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  effect record;
  recipient uuid;
begin
  for effect in
    select * from public.transition_notifications
    where from_status is not distinct from p_from and to_status = p_to
  loop
    if effect.recipient = 'VALIDATOR' then
      -- Le validateur désigné ; à défaut, le responsable du dossier — mieux vaut
      -- prévenir quelqu'un que personne.
      recipient := coalesce(p_occurrence.validator_id, p_occurrence.owner_id);
      if recipient is not null then
        insert into public.notifications (recipient_id, kind, occurrence_id, actor_id, reason)
        values (recipient, effect.kind, p_occurrence.id, public.app_actor_id(),
                case when effect.include_reason then p_reason else null end);
      end if;

    elsif effect.recipient = 'OWNER' then
      if p_occurrence.owner_id is not null then
        insert into public.notifications (recipient_id, kind, occurrence_id, actor_id, reason)
        values (p_occurrence.owner_id, effect.kind, p_occurrence.id, public.app_actor_id(),
                case when effect.include_reason then p_reason else null end);
      end if;

    elsif effect.recipient = 'DIRECTION' then
      -- Tous les comptes DIRECTION actifs. Le destinataire n'est pas une personne
      -- nommée mais une fonction : nommer quelqu'un ici le rendrait indispensable.
      insert into public.notifications (recipient_id, kind, occurrence_id, actor_id, reason)
      select distinct ur.user_id, effect.kind, p_occurrence.id, public.app_actor_id(),
             case when effect.include_reason then p_reason else null end
      from public.user_roles ur
      join public.roles r on r.id = ur.role_id
      where r.code = 'DIRECTION'
        and ur.revoked_at is null
        and (ur.expires_at is null or ur.expires_at > pg_catalog.now())
        -- Ne pas s'écrire à soi-même : l'auteur de l'action sait ce qu'il vient de faire.
        and ur.user_id is distinct from public.app_actor_id();
    end if;
  end loop;
end;
$fn$;

comment on function public.dispatch_transition_notifications is
  'Applique les effets déclarés dans transition_notifications. Appelée par le '
  'trigger qui journalise la transition : mêmes transaction, même verrou, même '
  'destin. Aucune branche par statut — la table dit qui prévenir.';

-- =============================================================================
-- 4. DOUBLE NIVEAU DE VALIDATION
-- =============================================================================

/*
 * Principe : la première validation n'est pas un changement d'état, c'est une
 * ÉTAPE. Elle est inscrite dans `occurrence_transitions` avec from = to =
 * PENDING_VALIDATION et `metadata->>'origin' = 'VALIDATION_STEP'`. Le compteur
 * de validations obtenues est donc porté par le journal lui-même, et non par une
 * colonne qu'il faudrait tenir à jour — le journal ne peut pas mentir, il est
 * append-only.
 *
 * L'épisode courant commence à la dernière entrée en PENDING_VALIDATION : un
 * dossier rejeté puis resoumis repart de zéro, ce qui est la seule lecture
 * défendable — la première validation portait sur un dossier différent.
 */

create or replace function public.validation_steps_obtained(p_occurrence_id uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $fn$
  -- ⚠️ L'épisode est délimité par l'IDENTIFIANT de la ligne, jamais par sa date.
  -- `created_at` vaut `now()`, c'est-à-dire l'heure de DÉBUT DE TRANSACTION : une
  -- validation, un rejet et une resoumission enchaînés dans la même transaction
  -- portent tous le même horodatage, et un `>=` sur la date compterait alors une
  -- validation périmée comme acquise. La séquence, elle, est strictement croissante.
  select count(*)::int
  from public.occurrence_transitions t
  where t.occurrence_id = p_occurrence_id
    and t.metadata ->> 'origin' = 'VALIDATION_STEP'
    and t.id > coalesce((
      select max(entry.id)
      from public.occurrence_transitions entry
      where entry.occurrence_id = p_occurrence_id
        and entry.to_status = 'PENDING_VALIDATION'
        and entry.from_status is distinct from 'PENDING_VALIDATION'
    ), 0);
$fn$;

comment on function public.validation_steps_obtained(uuid) is
  'Nombre de validations de premier niveau déjà obtenues pour l''épisode d''attente '
  'EN COURS. Compté dans le journal append-only plutôt que stocké dans une colonne : '
  'un compteur qu''on met à jour est un compteur qu''on peut désynchroniser. '
  'Un rejet suivi d''une nouvelle soumission remet le compte à zéro — la première '
  'validation portait sur un dossier qui n''existe plus.';

create or replace function public.validation_levels_required(p_occurrence_id uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $fn$
  select coalesce(ot.validation_levels, 1)
  from public.obligation_occurrences oc
  join public.obligation_types ot on ot.id = oc.obligation_type_id
  where oc.id = p_occurrence_id;
$fn$;

create or replace function public.is_direction(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $fn$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = p_user_id
      and r.code = 'DIRECTION'
      and ur.revoked_at is null
      and (ur.expires_at is null or ur.expires_at > pg_catalog.now())
  );
$fn$;

comment on function public.is_direction(uuid) is
  'Appartenance à la DIRECTION, rôle actif. Extraite parce que trois fonctions la '
  'posaient chacune de leur côté ; une règle d''appartenance dupliquée finit par '
  'diverger, et c''est toujours la variante la plus permissive qui l''emporte.';

create or replace function public.record_validation_step(p_occurrence_id uuid)
returns int
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  obtained int;
begin
  insert into public.occurrence_transitions
    (occurrence_id, from_status, to_status, actor_id, on_behalf_of_id, reason, metadata)
  values (
    p_occurrence_id,
    'PENDING_VALIDATION',
    'PENDING_VALIDATION',
    public.app_actor_id(),
    (
      select d.delegator_id
      from public.validation_delegations d
      where d.delegate_id = auth.uid()
        and d.revoked_at is null
        and current_date between d.starts_at and d.ends_at
      limit 1
    ),
    null,
    jsonb_build_object('origin', 'VALIDATION_STEP', 'level', 1)
  );

  obtained := public.validation_steps_obtained(p_occurrence_id);
  return obtained;
end;
$fn$;

comment on function public.record_validation_step(uuid) is
  'Inscrit une validation de premier niveau SANS changer l''état. Le dossier reste '
  'en attente, et l''historique porte la trace nominative de qui a validé quoi.';

-- =============================================================================
-- 5. LA FONCTION QUI DÉCIDE
-- =============================================================================

create or replace function public.evaluate_transition(
  p_occurrence_id uuid,
  p_to_status public.occurrence_status,
  p_reason text default null,
  p_reference_number text default null,
  p_late_reason_code public.late_reason_code default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $fn$
declare
  occ public.obligation_occurrences%rowtype;
  rule public.status_transition_rules%rowtype;
  occ_domain uuid;
  needs_proof boolean;
  missing text[];
  today_algiers date := (pg_catalog.now() at time zone 'Africa/Algiers')::date;
  reason_clean text := nullif(pg_catalog.btrim(coalesce(p_reason, '')), '');
  levels int;
  obtained int;
begin
  if not public.can_see_occurrence(p_occurrence_id) then
    -- Indistinguable d'un identifiant inexistant : l'écart de message permettrait
    -- d'énumérer les dossiers des autres domaines.
    return jsonb_build_object('outcome', 'NOT_FOUND');
  end if;

  select * into occ from public.obligation_occurrences where id = p_occurrence_id;
  if occ.id is null then
    return jsonb_build_object('outcome', 'NOT_FOUND');
  end if;

  if occ.status = p_to_status then
    return jsonb_build_object('outcome', 'NO_CHANGE', 'version', occ.version);
  end if;

  -- ── La transition existe-t-elle ? ─────────────────────────────────────────
  -- Lue dans status_transition_rules, jamais écrite en dur.
  select * into rule
  from public.status_transition_rules
  where from_status = occ.status and to_status = p_to_status;

  if rule.id is null then
    return jsonb_build_object(
      'outcome', 'INVALID_TRANSITION', 'from', occ.status, 'to', p_to_status);
  end if;

  -- ── Verrou ────────────────────────────────────────────────────────────────
  -- Une seule porte de sortie, celle de `enforce_occurrence_lock` : la
  -- réouverture d'un dossier archivé.
  if occ.is_locked and not (occ.status = 'ARCHIVED' and p_to_status = 'SUBMITTED') then
    return jsonb_build_object('outcome', 'LOCKED');
  end if;

  -- ── Habilitation ──────────────────────────────────────────────────────────
  occ_domain := public.obligation_domain_of_type(occ.obligation_type_id);

  if rule.required_permission = 'occurrence.validate' then
    -- can_validate_occurrence intègre le filet DIRECTION passé le délai d'attente.
    if not public.can_validate_occurrence(p_occurrence_id) then
      return jsonb_build_object('outcome', 'FORBIDDEN', 'permission', rule.required_permission);
    end if;
  elsif not public.has_permission_in_domain(rule.required_permission, occ_domain) then
    return jsonb_build_object('outcome', 'FORBIDDEN', 'permission', rule.required_permission);
  end if;

  -- ── Motif ─────────────────────────────────────────────────────────────────
  if rule.requires_reason and reason_clean is null then
    return jsonb_build_object('outcome', 'REASON_REQUIRED');
  end if;

  -- ── Complétude du dossier ─────────────────────────────────────────────────
  if p_to_status = 'PENDING_VALIDATION' then
    missing := public.occurrence_missing_items(p_occurrence_id);
    if pg_catalog.array_length(missing, 1) is not null then
      return jsonb_build_object('outcome', 'INCOMPLETE', 'missing', to_jsonb(missing));
    end if;
  end if;

  -- ── Séparation des pouvoirs, et niveaux de validation ─────────────────────
  if p_to_status = 'VALIDATED' then
    if public.self_validation_blocked(
         occ.obligation_type_id, occ.owner_id, public.current_profile_id()) then
      return jsonb_build_object('outcome', 'SELF_VALIDATION_BLOCKED');
    end if;

    levels := public.validation_levels_required(p_occurrence_id);
    obtained := public.validation_steps_obtained(p_occurrence_id);

    if levels > 1 then
      if obtained = 0 then
        -- Première validation : elle compte, mais ne change pas l'état.
        return jsonb_build_object(
          'outcome', 'ALLOWED', 'effect', 'PARTIAL_VALIDATION',
          'obtained', obtained, 'required', levels, 'version', occ.version);
      end if;

      -- Second niveau : réservé à la DIRECTION, par décision arrêtée.
      if not public.is_direction(auth.uid()) then
        return jsonb_build_object(
          'outcome', 'SECOND_LEVEL_REQUIRES_DIRECTION',
          'obtained', obtained, 'required', levels);
      end if;
    end if;
  end if;

  -- ── Dépôt : preuve, référence, motif de retard ────────────────────────────
  if p_to_status = 'SUBMITTED' and occ.status = 'VALIDATED' then
    select ot.requires_proof into needs_proof
    from public.obligation_types ot where ot.id = occ.obligation_type_id;

    if coalesce(needs_proof, false) then
      if nullif(pg_catalog.btrim(coalesce(p_reference_number, occ.reference_number, '')), '') is null then
        return jsonb_build_object('outcome', 'REFERENCE_REQUIRED');
      end if;
      if not exists (
        select 1 from public.documents d
        where d.occurrence_id = p_occurrence_id
          and d.document_kind = 'PREUVE_DEPOT'
          and d.deleted_at is null
      ) then
        return jsonb_build_object('outcome', 'PROOF_REQUIRED');
      end if;
    end if;

    -- ⚠️ Motif de retard OBLIGATOIRE au-delà de l'échéance légale. C'est le seul
    -- moment où l'information est encore fraîche ; réclamée plus tard, elle est
    -- reconstruite, donc fausse.
    if occ.legal_due_date < today_algiers
       and coalesce(p_late_reason_code, occ.late_reason_code) is null then
      return jsonb_build_object('outcome', 'LATE_REASON_REQUIRED', 'dueDate', occ.legal_due_date);
    end if;
  end if;

  return jsonb_build_object(
    'outcome', 'ALLOWED', 'effect', 'FULL', 'version', occ.version, 'label', rule.label);
end;
$fn$;

comment on function public.evaluate_transition is
  '⚠️ SOURCE UNIQUE de la décision « cette transition est-elle possible, et sinon '
  'pourquoi ». Consultée par `apply_occurrence_transition` avant d''écrire, et par '
  'le service TypeScript `canTransition` pour griser un bouton et en expliquer la '
  'raison. Rien n''est donc décidé deux fois : l''interface ne peut plus promettre '
  'ce que la base refusera, ni refuser ce qu''elle accepterait. '
  'STABLE et sans effet de bord : elle répond, elle n''agit pas.';

grant execute on function public.evaluate_transition(
  uuid, public.occurrence_status, text, text, public.late_reason_code) to authenticated;

-- =============================================================================
-- 6. LE TRIGGER APPLIQUE AUSSI LA RÈGLE DES DEUX NIVEAUX
-- =============================================================================

create or replace function public.validate_status_transition()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  rule public.status_transition_rules%rowtype;
  resolved_reason text;
  occ_domain uuid;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  select * into rule
    from public.status_transition_rules
   where from_status = old.status
     and to_status = new.status;

  if not found then
    raise exception 'Transition interdite : % → %.', old.status, new.status
      using errcode = '23514',
            hint = 'Les transitions autorisées sont des données : voir public.status_transition_rules.';
  end if;

  -- Contrôle d'habilitation. Ignoré hors session (auth.uid() NULL) : les jobs de
  -- src/server/jobs/ et les migrations n'ont pas d'utilisateur, et sont déjà
  -- contraints par ailleurs. Un appel authentifié, lui, est toujours vérifié.
  if auth.uid() is not null then
    occ_domain := public.obligation_domain_of_type(new.obligation_type_id);

    if rule.required_permission = 'occurrence.validate' then
      -- Passe par can_validate_occurrence : elle intègre le filet DIRECTION.
      if not public.can_validate_occurrence(new.id) then
        raise exception 'Permission % requise pour la transition % → %.',
          rule.required_permission, old.status, new.status
          using errcode = '42501';
      end if;
    elsif not public.has_permission_in_domain(rule.required_permission, occ_domain) then
      raise exception 'Permission % requise pour la transition % → %.',
        rule.required_permission, old.status, new.status
        using errcode = '42501';
    end if;

    -- ⚠️ DOUBLE NIVEAU. Vérifié ICI, dans le trigger, et pas seulement dans la
    -- fonction d'application : un détenteur de `occurrence.write` peut émettre un
    -- UPDATE direct sur la table, et la règle serait alors contournée par le seul
    -- fait de ne pas passer par la porte prévue.
    if new.status = 'VALIDATED' and public.validation_levels_required(new.id) > 1 then
      if public.validation_steps_obtained(new.id) = 0 then
        raise exception
          'Cette obligation exige deux validations : la première n''a pas été enregistrée.'
          using errcode = '23514';
      end if;
      if not public.is_direction(auth.uid()) then
        raise exception 'La seconde validation est réservée à la DIRECTION.'
          using errcode = '42501';
      end if;
    end if;
  end if;

  resolved_reason := coalesce(
    public.app_transition_reason(),
    case new.status
      when 'NOT_APPLICABLE' then new.na_reason
      when 'REJECTED' then new.rejection_reason
      else null
    end
  );

  if rule.requires_reason and (resolved_reason is null or btrim(resolved_reason) = '') then
    raise exception 'Motif obligatoire pour la transition % → %.', old.status, new.status
      using errcode = '23514',
            hint = 'Renseigner la colonne de motif, ou poser SET LOCAL conformia.transition_reason.';
  end if;

  if rule.locks_occurrence then
    new.is_locked := true;
    new.locked_at := now();
    new.locked_by := public.app_actor_id();
  end if;

  if old.status = 'ARCHIVED' and new.status = 'SUBMITTED' then
    new.is_locked := false;
    new.locked_at := null;
    new.locked_by := null;
  end if;

  return new;
end;
$fn$;

comment on function public.validate_status_transition() is
  'Autorise ou refuse un changement d''état : existence de la transition dans '
  'status_transition_rules, permission requise, motif obligatoire, et second '
  'niveau de validation lorsque l''obligation l''exige. AUCUNE transition et '
  'AUCUNE permission ne sont écrites en dur — toutes sont des données.';

-- =============================================================================
-- 7. LE JOURNAL DÉCLENCHE LES EFFETS
-- =============================================================================

create or replace function public.record_status_transition()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  previous_status public.occurrence_status;
  resolved_reason text;
begin
  if tg_op = 'INSERT' then
    previous_status := null;
  else
    if new.status is not distinct from old.status then
      return null;
    end if;
    previous_status := old.status;
  end if;

  resolved_reason := coalesce(
    public.app_transition_reason(),
    case new.status
      when 'NOT_APPLICABLE' then new.na_reason
      when 'REJECTED' then new.rejection_reason
      else null
    end
  );

  insert into public.occurrence_transitions
    (occurrence_id, from_status, to_status, actor_id, on_behalf_of_id, reason, metadata)
  values (
    new.id,
    previous_status,
    new.status,
    public.app_actor_id(),
    -- Action sous délégation : on conserve le délégant, sans effacer l'auteur réel.
    (
      select d.delegator_id
      from public.validation_delegations d
      where d.delegate_id = auth.uid()
        and d.revoked_at is null
        and current_date between d.starts_at and d.ends_at
      limit 1
    ),
    resolved_reason,
    jsonb_build_object('origin', case when tg_op = 'INSERT' then 'CREATION' else 'TRANSITION' end)
  );

  -- ⚠️ MÊME TRANSACTION que la transition et que son journal. Si la notification
  -- ne peut pas s'écrire, la transition entière est annulée. C'est délibéré :
  -- un validateur qui n'est jamais prévenu ne valide jamais, et le dossier
  -- expire sans que personne n'ait rien vu passer.
  if tg_op <> 'INSERT' then
    perform public.dispatch_transition_notifications(new, previous_status, new.status, resolved_reason);
  end if;

  return null;
end;
$fn$;

comment on function public.record_status_transition() is
  'Écrit le journal d''état PUIS déclenche les effets déclarés dans '
  'transition_notifications, dans la même transaction. En SECURITY DEFINER : la '
  'table n''accepte aucune écriture directe, pas même de service_role. Renseigne '
  'on_behalf_of_id quand l''auteur agit sous délégation active.';

-- =============================================================================
-- 8. APPLICATION D'UNE TRANSITION
-- =============================================================================

create or replace function public.apply_occurrence_transition(
  p_occurrence_id uuid,
  p_to_status public.occurrence_status,
  p_expected_version int,
  p_reason text default null,
  p_reference_number text default null,
  p_late_reason_code public.late_reason_code default null,
  p_late_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  occ public.obligation_occurrences%rowtype;
  verdict jsonb;
  reason_clean text := nullif(pg_catalog.btrim(coalesce(p_reason, '')), '');
  obtained int;
begin
  -- Verrou de ligne AVANT toute évaluation : deux validations concurrentes se
  -- sérialisent, et la seconde voit l'étape que la première vient d'inscrire.
  select * into occ
  from public.obligation_occurrences
  where id = p_occurrence_id
  for update;

  if occ.id is null then
    return jsonb_build_object('outcome', 'NOT_FOUND');
  end if;

  -- ⚠️ Verrouillage optimiste, AVANT l'évaluation : un conflit de version doit
  -- se dire tel quel, et non se déguiser en refus métier.
  if occ.version <> p_expected_version and occ.status <> p_to_status then
    return jsonb_build_object(
      'outcome', 'VERSION_CONFLICT', 'version', occ.version, 'status', occ.status);
  end if;

  -- ⚠️ AUCUNE règle n'est réévaluée ici : la décision appartient entièrement à
  -- evaluate_transition, que l'interface consulte aussi. Cette fonction
  -- TRANSPORTE, elle ne décide pas.
  verdict := public.evaluate_transition(
    p_occurrence_id, p_to_status, p_reason, p_reference_number, p_late_reason_code);

  if verdict ->> 'outcome' <> 'ALLOWED' then
    return verdict;
  end if;

  -- Première des deux validations : on inscrit l'étape, l'état ne bouge pas.
  if verdict ->> 'effect' = 'PARTIAL_VALIDATION' then
    obtained := public.record_validation_step(p_occurrence_id);
    return jsonb_build_object(
      'outcome', 'PARTIALLY_VALIDATED',
      'obtained', obtained,
      'required', (verdict ->> 'required')::int,
      'version', occ.version,
      'status', occ.status);
  end if;

  -- Motif transporté jusqu'au trigger, pour les transitions dont le motif n'a
  -- pas de colonne dédiée (réouverture d'archive, retour d'un dossier sans objet).
  perform pg_catalog.set_config('conformia.transition_reason', coalesce(reason_clean, ''), true);

  update public.obligation_occurrences
     set status = p_to_status,
         started_at = case
           when p_to_status = 'IN_PROGRESS' then coalesce(started_at, pg_catalog.now())
           else started_at end,
         submitted_for_validation_at = case
           when p_to_status = 'PENDING_VALIDATION' then pg_catalog.now()
           else submitted_for_validation_at end,
         validated_at = case
           when p_to_status = 'VALIDATED' then pg_catalog.now() else validated_at end,
         validated_by = case
           when p_to_status = 'VALIDATED' then public.app_actor_id() else validated_by end,
         submitted_at = case
           when p_to_status = 'SUBMITTED' then pg_catalog.now() else submitted_at end,
         submitted_by = case
           when p_to_status = 'SUBMITTED' then public.app_actor_id() else submitted_by end,
         reference_number = coalesce(
           nullif(pg_catalog.btrim(coalesce(p_reference_number, '')), ''), reference_number),
         late_reason_code = case
           when p_to_status = 'SUBMITTED' then coalesce(p_late_reason_code, late_reason_code)
           else late_reason_code end,
         late_reason = case
           when p_to_status = 'SUBMITTED'
             then coalesce(nullif(pg_catalog.btrim(coalesce(p_late_reason, '')), ''), late_reason)
           else late_reason end,
         rejection_reason = case
           when p_to_status = 'REJECTED' then reason_clean else rejection_reason end,
         na_reason = case
           when p_to_status = 'NOT_APPLICABLE' then reason_clean else na_reason end
   where id = p_occurrence_id
     and version = p_expected_version;

  if not found then
    return jsonb_build_object('outcome', 'VERSION_CONFLICT');
  end if;

  select * into occ from public.obligation_occurrences where id = p_occurrence_id;

  return jsonb_build_object(
    'outcome', 'APPLIED', 'version', occ.version, 'status', occ.status);
end;
$fn$;

comment on function public.apply_occurrence_transition is
  'TRANSPORT d''une transition, jamais sa décision : depuis 0010, toutes les '
  'règles sont dans `evaluate_transition`, qu''elle appelle. Elle n''ajoute que ce '
  'que PostgREST ne sait pas exprimer : verrou de ligne, version attendue, GUC de '
  'motif, colonnes annexes, et l''inscription d''une validation de premier niveau. '
  'SECURITY DEFINER car obligation_occurrences_update exige occurrence.write, que '
  'DIRECTION ne détient pas alors qu''elle détient occurrence.validate, '
  'occurrence.mark_na et occurrence.unlock : sans cela, ces trois actions seraient '
  'des boutons sans effet.';

-- =============================================================================
-- 9. FILE DE VALIDATION
-- =============================================================================

create or replace function public.pending_validation_count()
returns int
language sql
stable
security definer
set search_path = ''
as $fn$
  select count(*)::int
  from public.obligation_occurrences oc
  where oc.status = 'PENDING_VALIDATION'
    and oc.deleted_at is null
    and public.can_see_occurrence(oc.id)
    and public.can_validate_occurrence(oc.id)
    and not public.self_validation_blocked(
          oc.obligation_type_id, oc.owner_id, public.current_profile_id());
$fn$;

comment on function public.pending_validation_count() is
  'Compteur affiché dans la navigation. Applique EXACTEMENT les mêmes conditions '
  'que la file elle-même, séparation des pouvoirs comprise : un compteur qui '
  'annonce trois dossiers pour une file qui en montre deux détruit la confiance '
  'dans les deux.';

grant execute on function public.pending_validation_count() to authenticated;

create view public.validation_queue
  with (security_invoker = true)
  as
  select oc.id,
         oc.obligation_type_id,
         oc.period_key,
         oc.period_start,
         oc.legal_due_date,
         oc.internal_due_date,
         oc.status,
         oc.version,
         oc.owner_id,
         oc.validator_id,
         oc.submitted_for_validation_at,
         ot.code as obligation_code,
         ot.name as obligation_name,
         ot.criticality,
         ot.validation_levels,
         dom.code as domain_code,
         au.name as authority_name,
         owner.full_name as owner_name,
         public.validation_steps_obtained(oc.id) as validations_obtained,
         (oc.internal_due_date - (pg_catalog.now() at time zone 'Africa/Algiers')::date)
           as days_to_internal
  from public.obligation_occurrences oc
  join public.obligation_types ot on ot.id = oc.obligation_type_id
  left join public.domains dom on dom.id = ot.domain_id
  left join public.authorities au on au.id = ot.authority_id
  left join public.profiles owner on owner.id = oc.owner_id
  where oc.status = 'PENDING_VALIDATION'
    and oc.deleted_at is null
    and public.can_validate_occurrence(oc.id)
    and not public.self_validation_blocked(
          oc.obligation_type_id, oc.owner_id, public.current_profile_id());

comment on view public.validation_queue is
  'Dossiers en attente de la validation de l''appelant, délégations comprises — '
  'c''est `can_validate_occurrence` qui les intègre, et non un filtre recopié ici. '
  'security_invoker : la politique des occurrences s''applique, donc le '
  'cloisonnement par domaine. La séparation des pouvoirs est appliquée dans la vue '
  'ET par le trigger : proposer un dossier qu''on ne pourra pas valider est une '
  'promesse que la base démentira au clic.';

grant select on public.validation_queue to authenticated;

-- -----------------------------------------------------------------------------
-- Le compteur de navigation s'aligne sur la file
-- -----------------------------------------------------------------------------

/*
 * ⚠️ DIVERGENCE CORRIGÉE. Depuis 0005, le compteur « à valider » de la barre
 * latérale comptait les dossiers en attente que l'appelant peut valider — mais
 * SANS écarter ceux dont il est lui-même le préparateur. La file, elle, les
 * écarte, puisque la séparation des pouvoirs les lui interdit. Un responsable
 * qui prépare ses propres dossiers voyait donc une pastille annonçant trois
 * dossiers pour une file qui n'en montrait qu'un.
 *
 * Le compteur ne recopie plus la condition : il appelle la MÊME fonction que la
 * file. Deux définitions d'un même nombre finissent toujours par diverger.
 */
create or replace function public.navigation_counters()
returns table (
  overdue int,
  pending_validation int,
  my_tasks int
)
language sql
stable
security invoker
set search_path = ''
as $fn$
  select
    -- Même définition que occurrence_list.is_overdue : la pastille de la barre
    -- latérale et la colonne de la liste doivent donner le même nombre.
    count(*) filter (
      where oc.legal_due_date < (now() at time zone 'Africa/Algiers')::date
        and not (oc.status = any (public.overdue_exempt_statuses()))
    )::int,
    public.pending_validation_count(),
    count(*) filter (
      where oc.owner_id = public.current_profile_id()
        and oc.status in ('TODO', 'IN_PROGRESS', 'REJECTED')
    )::int
  from public.obligation_occurrences oc
  where oc.deleted_at is null
$fn$;

comment on function public.navigation_counters() is
  '⚠️ SECURITY INVOKER. Les trois compteurs ne portent que sur les lignes que la RLS
   laisse voir. Le compteur de retard emploie overdue_exempt_statuses(), et celui
   des validations appelle pending_validation_count() — la MÊME fonction que la
   file /validation. Un écart entre une pastille et l''écran qu''elle annonce se
   lit comme un défaut, et détruit la confiance dans les deux.';

-- =============================================================================
-- 10. DÉLÉGATIONS — révocation
-- =============================================================================

create or replace function public.revoke_validation_delegation(
  p_delegation_id uuid,
  p_reason text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  target public.validation_delegations%rowtype;
  affected int;
begin
  select * into target from public.validation_delegations where id = p_delegation_id;
  if target.id is null then
    raise exception 'Délégation introuvable.' using errcode = '42501';
  end if;

  -- Le délégant reprend ses droits quand il veut ; la DIRECTION arbitre.
  if not (target.delegator_id = public.current_profile_id() or public.is_direction(auth.uid())) then
    raise exception 'Révocation réservée au délégant ou à la Direction.' using errcode = '42501';
  end if;

  if p_reason is null or length(trim(p_reason)) < 10 then
    raise exception 'Un motif d''au moins 10 caractères est requis.' using errcode = '22023';
  end if;

  update public.validation_delegations
  set revoked_at = pg_catalog.now(),
      revoked_by = public.current_profile_id(),
      reason = target.reason || ' — révoquée : ' || trim(p_reason)
  where id = p_delegation_id and revoked_at is null;

  get diagnostics affected = row_count;
  return affected = 1;
end;
$fn$;

comment on function public.revoke_validation_delegation(uuid, text) is
  'Révocation immédiate. Motif obligatoire, concaténé au motif d''origine : le '
  'journal doit dire pourquoi la délégation a été ouverte ET pourquoi elle a été '
  'refermée. La ligne est CONSERVÉE — une délégation supprimée effacerait la '
  'justification des actions faites sous son couvert.';

grant execute on function public.revoke_validation_delegation(uuid, text) to authenticated;
