-- =============================================================================
-- 0011 — TABLEAU DE BORD ET ADMINISTRATION
--
-- Deux modules, une seule migration, parce qu'ils partagent trois mécanismes :
-- les vues matérialisées, les notifications, et le journal d'audit.
--
-- ⚠️ RAPPEL CENTRAL SUR LES VUES MATÉRIALISÉES. PostgreSQL n'applique PAS la RLS
-- à une matview. Toutes celles créées ici sont donc agrégées PAR DOMAINE, ne
-- reçoivent AUCUN grant, et ne sont lisibles que par une fonction
-- `*_for_caller()` qui réapplique le cloisonnement ligne par ligne. C'est la
-- convention posée en 0007 et elle est reconduite à l'identique : un agrégat
-- fuit aussi sûrement qu'une liste, et un COUNT par domaine renseigne sur la
-- charge de travail d'un service qu'on n'a pas le droit de voir.
-- =============================================================================

-- =============================================================================
-- 1. VOCABULAIRE DES NOTIFICATIONS
-- =============================================================================

-- Les trois motifs de 0010, plus ceux que l'administration introduit.
alter table public.notifications drop constraint notifications_kind_check;
alter table public.notifications add constraint notifications_kind_check
  check (kind in (
    'VALIDATION_REQUESTED', 'OCCURRENCE_REJECTED', 'OCCURRENCE_UNLOCKED',
    'MFA_RESET', 'HOLIDAY_CALENDAR_CHANGED', 'ROLE_GRANTED', 'ROLE_REVOKED'));

-- =============================================================================
-- 2. SAUVEGARDES — le socle de l'alerte, pas la sauvegarde elle-même
-- =============================================================================

create table public.backup_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null check (status in ('RUNNING', 'SUCCEEDED', 'FAILED')),
  size_bytes bigint,
  detail text
);

comment on table public.backup_runs is
  '⚠️ Ce projet NE SAUVEGARDE RIEN. Cette table est le journal qu''un dispositif '
  'de sauvegarde — externe, ou la tâche à venir — doit alimenter, et sur lequel '
  'le bandeau d''alerte s''appuie. '
  'Conséquence VOULUE et à connaître : tant que personne n''y écrit, l''alerte '
  '« aucune sauvegarde réussie depuis 36 h » est allumée en permanence. C''est le '
  'comportement juste : l''absence de sauvegarde est exactement ce qu''une alerte '
  'de sauvegarde doit signaler. Une table vide traitée comme « tout va bien » '
  'transformerait ce bandeau en décor.';

create index backup_runs_recent_idx on public.backup_runs (started_at desc);

alter table public.backup_runs enable row level security;
revoke insert, update, delete on public.backup_runs from public, anon, authenticated;
grant select on public.backup_runs to authenticated;

create policy backup_runs_select on public.backup_runs
  for select to authenticated
  using (public.is_active_user() and public.has_permission('settings.manage'));
comment on policy backup_runs_select on public.backup_runs is
  'Exploitation technique : réservé à qui administre l''installation.';

-- =============================================================================
-- 3. DÉSACTIVATION D'UN COMPTE — refusée tant qu'il porte du travail
-- =============================================================================

create or replace function public.open_task_count(p_user_id uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $fn$
  -- ⚠️ `overdue_exempt_statuses()` porte un nom de compteur de retard, mais
  -- énumère exactement les états TERMINÉS : déposé, archivé, sans objet. « Encore
  -- ouvert » et « n'arrête pas le compteur de retard » ont ici la même réponse, et
  -- 0007 a justement supprimé la seconde liste parce que deux définitions
  -- donnaient deux chiffres pour la même question. On réemploie donc celle-ci.
  select count(*)::int
  from public.obligation_occurrences oc
  where oc.deleted_at is null
    and not (oc.status = any (public.overdue_exempt_statuses()))
    and (oc.owner_id = p_user_id or oc.validator_id = p_user_id);
$fn$;

comment on function public.open_task_count(uuid) is
  'Dossiers encore ouverts dont la personne est responsable OU validateur. '
  'Les deux rôles comptent : désactiver le seul validateur d''un dossier le bloque '
  'aussi sûrement que d''en désactiver le préparateur.';

grant execute on function public.open_task_count(uuid) to authenticated;

create or replace function public.enforce_deactivation_requires_handover()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  remaining int;
begin
  if new.deactivated_at is null or old.deactivated_at is not null then
    return new;
  end if;

  remaining := public.open_task_count(new.id);

  if remaining > 0 then
    raise exception
      'Désactivation refusée : % dossier(s) ouvert(s) restent affectés à ce compte.', remaining
      using errcode = '23514',
            hint = 'Réaffecter les dossiers à une autre personne avant de désactiver.';
  end if;

  return new;
end;
$fn$;

comment on function public.enforce_deactivation_requires_handover() is
  '⚠️ Un compte désactivé qui porte encore des dossiers les rend ORPHELINS : ils '
  'restent dus, plus personne ne les voit dans « mes tâches », et l''échéance '
  'passe sans que quiconque ait été prévenu. La réaffectation est donc un '
  'PRÉALABLE, imposé en base — l''écran qui demande un destinataire est un '
  'confort, ce trigger est la garantie.';

create trigger trg_profiles_deactivation_handover
  before update on public.profiles
  for each row execute function public.enforce_deactivation_requires_handover();

/**
 * Désactive un compte, en réaffectant d'abord ce qu'il porte.
 *
 * ⚠️ EXISTE PARCE QUE `profiles_update` (0002) ne laisse modifier QUE son propre
 * profil — et c'est une bonne politique : personne ne doit pouvoir réécrire la
 * fiche d'un collègue. Un administrateur n'a donc aucun moyen de désactiver
 * quelqu'un par un UPDATE, et il ne doit pas en avoir : il a besoin de CE
 * geste-ci, borné, et d'aucun autre.
 *
 * La réaffectation et la désactivation sont dans la MÊME transaction. Séparées,
 * elles laisseraient une fenêtre où le compte est fermé et les dossiers encore
 * à lui — exactement l'état d'orphelinat que le trigger existe pour empêcher.
 */
create or replace function public.deactivate_user(
  p_user_id uuid,
  p_reason text,
  p_handover_to uuid default null
)
returns int
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  moved int := 0;
begin
  if not public.has_permission('user.manage') then
    raise exception 'Désactivation refusée : user.manage requis.' using errcode = '42501';
  end if;
  if p_reason is null or length(trim(p_reason)) < 10 then
    raise exception 'Un motif d''au moins 10 caractères est requis.' using errcode = '22023';
  end if;

  -- Se désactiver soi-même verrouillerait l'installation si l'on est le dernier
  -- administrateur, et il n'existe aucun chemin de retour.
  if p_user_id = public.current_profile_id() then
    raise exception 'Un administrateur ne peut pas désactiver son propre compte.'
      using errcode = '42501';
  end if;

  if p_handover_to is not null then
    if p_handover_to = p_user_id then
      raise exception 'Le destinataire doit être une autre personne.' using errcode = '22023';
    end if;

    update public.obligation_occurrences
    set owner_id = case when owner_id = p_user_id then p_handover_to else owner_id end,
        validator_id = case when validator_id = p_user_id then p_handover_to else validator_id end,
        updated_at = now()
    where deleted_at is null
      and not (status = any (public.overdue_exempt_statuses()))
      and (owner_id = p_user_id or validator_id = p_user_id);

    get diagnostics moved = row_count;
  end if;

  -- Le trigger `enforce_deactivation_requires_handover` refuse s'il reste
  -- quoi que ce soit : c'est lui la garantie, pas la réaffectation ci-dessus.
  update public.profiles
  set deactivated_at = now(), deactivated_by = public.current_profile_id(), is_active = false
  where id = p_user_id;

  insert into public.audit_log (
    actor_id, actor_email, action, entity_table, entity_id_ref, after
  )
  values (
    auth.uid(),
    (select pr.email::text from public.profiles pr where pr.id = auth.uid()),
    'UPDATE', 'profiles', p_user_id::text,
    jsonb_build_object('deactivated', true, 'reason', trim(p_reason),
                       'handover_to', p_handover_to, 'reassigned', moved)
  );

  return moved;
end;
$fn$;

comment on function public.deactivate_user(uuid, text, uuid) is
  'Réaffecte puis désactive, en une transaction. Motif obligatoire. Refuse '
  'l''auto-désactivation. Le destinataire est facultatif POUR LA FONCTION — un '
  'compte sans dossier n''en a pas besoin — mais le trigger refusera la '
  'désactivation s''il en reste, ce qui rend le destinataire obligatoire dans les '
  'seuls cas où il l''est réellement.';

grant execute on function public.deactivate_user(uuid, text, uuid) to authenticated;

-- =============================================================================
-- 4. RÉINITIALISATION DU SECOND FACTEUR
-- =============================================================================

create or replace function public.reset_user_mfa(p_user_id uuid, p_reason text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  target record;
  affected int;
begin
  if not public.has_permission('user.manage') then
    raise exception 'Réinitialisation MFA refusée : user.manage requis.' using errcode = '42501';
  end if;
  if p_reason is null or length(trim(p_reason)) < 10 then
    raise exception 'Un motif d''au moins 10 caractères est requis.' using errcode = '22023';
  end if;

  select id, email, full_name into target from public.profiles where id = p_user_id;
  if target.id is null then
    raise exception 'Compte introuvable.' using errcode = '42501';
  end if;

  update public.profiles set mfa_enrolled = false where id = p_user_id;
  get diagnostics affected = row_count;

  -- ⚠️ Retirer le second facteur de quelqu'un est le geste qui permet de prendre
  -- sa place. Il est donc journalisé nommément, et la DIRECTION en est informée
  -- SANS pouvoir l'empêcher : le contre-pouvoir est la visibilité, pas le veto.
  insert into public.audit_log (
    actor_id, actor_email, action, entity_table, entity_id_ref, after
  )
  values (
    auth.uid(),
    (select p.email::text from public.profiles p where p.id = auth.uid()),
    'MFA_RESET', 'profiles', p_user_id::text,
    jsonb_build_object('reason', trim(p_reason), 'target_email', target.email::text)
  );

  insert into public.notifications (recipient_id, kind, actor_id, reason)
  select distinct ur.user_id, 'MFA_RESET', public.app_actor_id(),
         'Second facteur réinitialisé pour ' || coalesce(target.full_name, target.email::text)
         || ' — ' || trim(p_reason)
  from public.user_roles ur
  join public.roles r on r.id = ur.role_id
  where r.code = 'DIRECTION'
    and ur.revoked_at is null
    and (ur.expires_at is null or ur.expires_at > now());

  return affected = 1;
end;
$fn$;

comment on function public.reset_user_mfa(uuid, text) is
  'Retire l''enrôlement du second facteur. Motif obligatoire, entrée d''audit '
  'nominative, DIRECTION notifiée. Aucune de ces trois traces n''est facultative.';

grant execute on function public.reset_user_mfa(uuid, text) to authenticated;

-- =============================================================================
-- 5. INVITATIONS
-- =============================================================================

create table public.user_invitations (
  id uuid primary key default gen_random_uuid(),
  email extensions.citext not null,
  full_name text not null,
  department_id uuid references public.departments (id) on delete restrict,
  role_id uuid not null references public.roles (id) on delete restrict,
  domain_id uuid references public.domains (id) on delete restrict,
  role_expires_at timestamptz,
  invited_by uuid not null references public.profiles (id) on delete restrict,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '7 days',
  dispatched_at timestamptz,
  accepted_at timestamptz,
  cancelled_at timestamptz,
  constraint user_invitations_single_outcome
    check (num_nonnulls(accepted_at, cancelled_at) <= 1)
);

comment on table public.user_invitations is
  '⚠️ CRÉATION DE COMPTE PAR INVITATION, JAMAIS PAR MOT DE PASSE ADMINISTRATEUR. '
  'Un mot de passe choisi par un tiers est un mot de passe connu d''un tiers : la '
  'personne ne peut plus répondre de ce qui est fait sous son nom, et toute la '
  'traçabilité du produit s''effondre avec cette garantie. '
  'L''écran inscrit ici l''intention ; la création du compte d''authentification et '
  'l''envoi du courriel sont faits par `src/server/jobs/`, seul endroit détenant '
  'la clé de service (CLAUDE.md §6). L''invitation est donc une FILE, pas un envoi '
  'immédiat — et `dispatched_at` dit ce qui est réellement parti.';
comment on column public.user_invitations.role_expires_at is
  'Expiration du rôle attribué à l''acceptation. Obligatoire pour les rôles '
  'temporaires — la contrainte est vérifiée à l''invitation, et de nouveau par '
  'enforce_role_max_duration au moment de l''attribution réelle.';

create index user_invitations_pending_idx
  on public.user_invitations (created_at desc)
  where dispatched_at is null and cancelled_at is null;
create unique index user_invitations_active_email_idx
  on public.user_invitations (email)
  where accepted_at is null and cancelled_at is null;

create trigger trg_audit
  after insert or update or delete on public.user_invitations
  for each row execute function public.audit_trigger();

alter table public.user_invitations enable row level security;
grant select, insert, update on public.user_invitations to authenticated;

create policy user_invitations_select on public.user_invitations
  for select to authenticated
  using (public.is_active_user() and public.has_permission('user.manage'));

create policy user_invitations_insert on public.user_invitations
  for insert to authenticated
  with check (
    public.is_active_user()
    and public.has_permission('user.manage')
    and invited_by = public.current_profile_id()
  );

create policy user_invitations_update on public.user_invitations
  for update to authenticated
  using (public.is_active_user() and public.has_permission('user.manage'))
  with check (public.has_permission('user.manage'));

comment on policy user_invitations_insert on public.user_invitations is
  'On invite sous son propre nom : `invited_by` ne peut pas être usurpé.';

/*
 * Une invitation portant un rôle temporaire DOIT porter une expiration.
 *
 * ⚠️ Le contrôle est répété ici alors que `enforce_role_max_duration` le fera à
 * l'attribution. Ce n'est pas une duplication de règle mais une anticipation :
 * sans lui, l'invitation partirait, la personne créerait son compte, et
 * l'attribution du rôle échouerait — laissant un compte sans droits et personne
 * pour comprendre pourquoi. La borne, elle, reste une donnée de
 * `roles.max_duration_days`, lue et non recopiée.
 */
create or replace function public.enforce_invitation_role_duration()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  max_days int;
  role_code text;
begin
  select r.max_duration_days, r.code into max_days, role_code
  from public.roles r where r.id = new.role_id;

  if max_days is null then
    return new;
  end if;

  if new.role_expires_at is null then
    raise exception 'Le rôle % exige une date d''expiration (maximum % jours).',
      role_code, max_days using errcode = '23514';
  end if;
  if new.role_expires_at > new.created_at + make_interval(days => max_days) then
    raise exception 'Le rôle % est limité à % jours.', role_code, max_days
      using errcode = '23514';
  end if;

  return new;
end;
$fn$;

create trigger trg_invitation_role_duration
  before insert or update on public.user_invitations
  for each row execute function public.enforce_invitation_role_duration();

-- =============================================================================
-- 6. MATRICE DES RÔLES — désormais modifiable, sous conditions
-- =============================================================================

/*
 * ⚠️ REVIREMENT ASSUMÉ. 0002 disait : « Aucune politique d'écriture — la matrice
 * des rôles système ne se modifie pas à chaud. » L'écran d'administration des
 * rôles demandé ici exige l'inverse.
 *
 * Le compromis retenu : la matrice devient modifiable, mais
 *   • seul `role.manage` écrit ;
 *   • un rôle SYSTÈME ne peut être ni supprimé ni renommé (trigger ci-dessous) ;
 *   • chaque modification est auditée ligne par ligne.
 *
 * Ce qui n'est PAS protégé, et doit être dit : rien n'empêche de retirer à
 * DIRECTION la permission `occurrence.validate`. Une matrice modifiable est une
 * matrice qu'on peut casser ; l'écran affiche un avertissement chiffré avant
 * toute réduction touchant des comptes actifs, et l'audit permet de revenir en
 * arrière. Verrouiller davantage reviendrait à ne pas livrer l'écran.
 */
-- Le trigger d'audit existe déjà sur cette table depuis 0003 : la matrice était
-- déjà surveillée, elle était simplement en lecture seule.
grant insert, delete on public.role_permissions to authenticated;

create policy role_permissions_insert on public.role_permissions
  for insert to authenticated
  with check (public.is_active_user() and public.has_permission('role.manage'));

create policy role_permissions_delete on public.role_permissions
  for delete to authenticated
  using (public.is_active_user() and public.has_permission('role.manage'));

comment on policy role_permissions_insert on public.role_permissions is
  'Édition de la matrice, réservée à role.manage. Chaque case cochée ou décochée '
  'produit une entrée d''audit : une extension de droits doit être reconstituable.';

create or replace function public.protect_system_roles()
returns trigger
language plpgsql
set search_path = ''
as $fn$
begin
  if tg_op = 'DELETE' then
    if old.is_system then
      raise exception 'Le rôle système % ne peut pas être supprimé.', old.code
        using errcode = '42501';
    end if;
    return old;
  end if;

  if old.is_system and (new.code is distinct from old.code
                        or new.is_system is distinct from old.is_system) then
    raise exception 'Le code d''un rôle système est immuable.'
      using errcode = '42501';
  end if;

  return new;
end;
$fn$;

comment on function public.protect_system_roles() is
  'Un rôle système est un point d''ancrage : `roles.code` est comparé en dur dans '
  'les fonctions d''autorisation (DIRECTION notamment). Le renommer ou le '
  'supprimer romprait ces comparaisons en silence. Ses PERMISSIONS, elles, '
  'restent modifiables — c''est le sens de l''écran.';

create trigger trg_roles_protect_system
  before update or delete on public.roles
  for each row execute function public.protect_system_roles();

/** Comptes actifs qu'une réduction de droits toucherait — pour avertir avant. */
create or replace function public.role_holder_count(p_role_id uuid)
returns int
language sql
stable
security definer
set search_path = ''
as $fn$
  select count(distinct ur.user_id)::int
  from public.user_roles ur
  join public.profiles p on p.id = ur.user_id
  where ur.role_id = p_role_id
    and ur.revoked_at is null
    and (ur.expires_at is null or ur.expires_at > now())
    and p.deactivated_at is null;
$fn$;

grant execute on function public.role_holder_count(uuid) to authenticated;

-- =============================================================================
-- 7. JOURS FÉRIÉS
-- =============================================================================

alter table public.holidays
  add column if not exists created_by uuid references public.profiles (id) on delete restrict;

create trigger trg_audit
  after insert or update or delete on public.holidays
  for each row execute function public.audit_trigger();

/*
 * Fêtes civiles à DATE FIXE, injectées comme récurrentes.
 *
 * ⚠️ Les fêtes religieuses ne sont PAS ici, et ne peuvent pas y être : Aïd
 * el-Fitr, Aïd el-Adha, Awal Moharem, Achoura et Mawlid Ennabaoui suivent le
 * calendrier hégirien et sont fixées chaque année par décret. Les calculer
 * serait inventer une règle réglementaire ; les figer serait pire. Elles sont
 * saisies à la main, et la tâche annuelle du 1er décembre existe précisément
 * pour que personne n'oublie de le faire.
 */
insert into public.holidays (holiday_date, label, is_recurring, source) values
  (date '2026-01-01', 'Nouvel an',                       true, 'Fête civile à date fixe'),
  (date '2026-01-12', 'Yennayer — nouvel an amazigh',    true, 'Fête civile à date fixe'),
  (date '2026-05-01', 'Fête du Travail',                 true, 'Fête civile à date fixe'),
  (date '2026-07-05', 'Fête de l''Indépendance',         true, 'Fête civile à date fixe'),
  (date '2026-11-01', 'Anniversaire de la Révolution',   true, 'Fête civile à date fixe')
on conflict (holiday_date) do nothing;

/**
 * Applique des échéances recalculées, toutes obligations confondues.
 *
 * ⚠️ Diffère de `recalculate_todo_due_dates` (0006), qui ne porte que sur UNE
 * obligation : un jour férié ajouté déplace potentiellement les échéances de
 * toutes. Les quatre bornes sont les mêmes, et pour la même raison — on ne
 * déplace pas le sol sous les pieds de quelqu'un qui a déjà commencé.
 */
create or replace function public.apply_due_date_updates(p_updates jsonb, p_reason text)
returns int
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  updated_count int;
begin
  if not public.has_permission('referential.manage') then
    raise exception 'Recalcul refusé : referential.manage requis.' using errcode = '42501';
  end if;
  if p_updates is null or jsonb_typeof(p_updates) <> 'array' then
    raise exception 'Recalcul refusé : liste de mises à jour attendue.' using errcode = '22023';
  end if;

  with proposed as (
    select (item ->> 'occurrence_id')::uuid as occurrence_id,
           (item ->> 'legal_due_date')::date as legal_due_date,
           (item ->> 'internal_due_date')::date as internal_due_date
    from jsonb_array_elements(p_updates) as item
  ),
  applied as (
    update public.obligation_occurrences oc
       set legal_due_date = p.legal_due_date,
           internal_due_date = p.internal_due_date,
           updated_at = now()
      from proposed p
     where oc.id = p.occurrence_id
       and oc.status = 'TODO'
       and oc.is_locked = false
       and oc.deleted_at is null
       and (oc.legal_due_date is distinct from p.legal_due_date
            or oc.internal_due_date is distinct from p.internal_due_date)
    returning oc.id, oc.owner_id
  ),
  notified as (
    -- Le responsable doit apprendre que SON échéance a bougé. Un calendrier qui
    -- se déplace en silence est pire qu'un calendrier faux : on continue de se
    -- fier à la date qu'on avait notée.
    insert into public.notifications (recipient_id, kind, occurrence_id, actor_id, reason)
    select a.owner_id, 'HOLIDAY_CALENDAR_CHANGED', a.id, public.app_actor_id(), p_reason
    from applied a
    where a.owner_id is not null
    returning 1
  )
  select count(*) into updated_count from applied;

  return updated_count;
end;
$fn$;

comment on function public.apply_due_date_updates(jsonb, text) is
  'Propage des échéances recalculées aux SEULES occurrences TODO non verrouillées, '
  'et prévient leurs responsables. Le calcul lui-même est fait par le service de '
  'planification, qui connaît les règles d''échéance et le calendrier — la base '
  'applique, elle ne recalcule pas.';

grant execute on function public.apply_due_date_updates(jsonb, text) to authenticated;

-- =============================================================================
-- 8. VUES MATÉRIALISÉES DU TABLEAU DE BORD
-- =============================================================================

/*
 * ⚠️ AUCUNE de ces vues n'est soumise à la RLS — PostgreSQL ne l'applique pas
 * aux matviews. Toutes sont donc agrégées PAR DOMAINE, ne reçoivent aucun grant,
 * et ne sont lisibles que par les fonctions `*_for_caller()` plus bas.
 */

-- ── Conformité mensuelle, 12 mois glissants ─────────────────────────────────
create materialized view public.dashboard_compliance_monthly as
select
  ot.domain_id,
  date_trunc('month', oc.legal_due_date)::date as month,
  count(*)::int as due_count,
  count(*) filter (
    where oc.submitted_at is not null
      and (oc.submitted_at at time zone 'Africa/Algiers')::date <= oc.legal_due_date
  )::int as on_time_count
from public.obligation_occurrences oc
join public.obligation_types ot on ot.id = oc.obligation_type_id
where oc.deleted_at is null
  and oc.status <> 'NOT_APPLICABLE'
  and oc.legal_due_date >= (date_trunc('month', now() at time zone 'Africa/Algiers') - interval '11 months')::date
  and oc.legal_due_date < (date_trunc('month', now() at time zone 'Africa/Algiers') + interval '1 month')::date
group by ot.domain_id, date_trunc('month', oc.legal_due_date);

comment on materialized view public.dashboard_compliance_monthly is
  '⚠️ NON soumise à la RLS. Taux de conformité = déposées DANS LES DÉLAIS sur '
  'échues. Les dossiers sans objet sont exclus du dénominateur : les compter '
  'comme échues ferait chuter le taux pour une raison qui n''a rien à voir avec '
  'la conformité. La date de dépôt est ramenée au fuseau d''Alger avant '
  'comparaison — en UTC, un dépôt du 20 à 23 h 30 locale paraîtrait fait le 21.';

create unique index dashboard_compliance_monthly_key_idx
  on public.dashboard_compliance_monthly (domain_id, month) nulls not distinct;
revoke all on public.dashboard_compliance_monthly from public, anon, authenticated;

-- ── Charge à venir, par semaine ─────────────────────────────────────────────
create materialized view public.dashboard_upcoming_load as
select
  ot.domain_id,
  date_trunc('week', oc.internal_due_date)::date as week_start,
  count(*)::int as total,
  count(*) filter (where oc.status = 'TODO')::int as not_started
from public.obligation_occurrences oc
join public.obligation_types ot on ot.id = oc.obligation_type_id
where oc.deleted_at is null
  and not (oc.status = any (public.overdue_exempt_statuses()))
  and oc.internal_due_date >= (now() at time zone 'Africa/Algiers')::date
  and oc.internal_due_date < (now() at time zone 'Africa/Algiers')::date + 84
group by ot.domain_id, date_trunc('week', oc.internal_due_date);

create unique index dashboard_upcoming_load_key_idx
  on public.dashboard_upcoming_load (domain_id, week_start) nulls not distinct;
revoke all on public.dashboard_upcoming_load from public, anon, authenticated;

-- ── Motifs de retard ────────────────────────────────────────────────────────
create materialized view public.dashboard_late_reasons as
select
  ot.domain_id,
  oc.late_reason_code,
  count(*)::int as total
from public.obligation_occurrences oc
join public.obligation_types ot on ot.id = oc.obligation_type_id
where oc.deleted_at is null
  and oc.late_reason_code is not null
group by ot.domain_id, oc.late_reason_code;

comment on materialized view public.dashboard_late_reasons is
  'L''indicateur le plus actionnable du produit : il dit POURQUOI les retards se '
  'produisent, ce qu''aucun taux ne dit. Alimenté par le motif obligatoire exigé '
  'au dépôt tardif — c''est la seule raison pour laquelle ce motif est obligatoire.';

create unique index dashboard_late_reasons_key_idx
  on public.dashboard_late_reasons (domain_id, late_reason_code) nulls not distinct;
revoke all on public.dashboard_late_reasons from public, anon, authenticated;

-- ── Charge par service et par personne ──────────────────────────────────────
create materialized view public.dashboard_workload as
select
  ot.domain_id,
  p.department_id,
  oc.owner_id,
  count(*)::int as open_total,
  count(*) filter (
    where oc.internal_due_date < (now() at time zone 'Africa/Algiers')::date
  )::int as late_total
from public.obligation_occurrences oc
join public.obligation_types ot on ot.id = oc.obligation_type_id
left join public.profiles p on p.id = oc.owner_id
where oc.deleted_at is null
  and not (oc.status = any (public.overdue_exempt_statuses()))
group by ot.domain_id, p.department_id, oc.owner_id;

create unique index dashboard_workload_key_idx
  on public.dashboard_workload (domain_id, department_id, owner_id) nulls not distinct;
revoke all on public.dashboard_workload from public, anon, authenticated;

-- ── Complétude documentaire, et ancienneté des validations ──────────────────
create materialized view public.dashboard_health as
select
  ot.domain_id,
  count(*) filter (where oc.status = 'PENDING_VALIDATION')::int as pending_validation,
  coalesce(avg(
    extract(epoch from (now() - oc.submitted_for_validation_at)) / 86400
  ) filter (where oc.status = 'PENDING_VALIDATION'), 0)::numeric(10, 2) as pending_avg_days,
  coalesce(sum(ci.required_total), 0)::int as documents_required,
  coalesce(sum(ci.provided_total), 0)::int as documents_provided
from public.obligation_occurrences oc
join public.obligation_types ot on ot.id = oc.obligation_type_id
left join lateral (
  select count(*) filter (where c.is_mandatory)::int as required_total,
         count(*) filter (where c.is_mandatory and c.is_checked)::int as provided_total
  from public.occurrence_checklist_items c
  where c.occurrence_id = oc.id
) ci on true
where oc.deleted_at is null
  and not (oc.status = any (public.overdue_exempt_statuses()))
group by ot.domain_id;

comment on materialized view public.dashboard_health is
  'Ancienneté MOYENNE des dossiers en attente, et complétude documentaire. '
  'La complétude compte les pièces OBLIGATOIRES cochées sur obligatoires '
  'attendues — `is_checked` étant lui-même une dérivation des pièces réellement '
  'déposées depuis 0008, jamais une case cliquée à la main.';

create unique index dashboard_health_key_idx
  on public.dashboard_health (domain_id) nulls not distinct;
revoke all on public.dashboard_health from public, anon, authenticated;

-- -----------------------------------------------------------------------------
-- Accesseurs : la SEULE porte, et la seule barrière
-- -----------------------------------------------------------------------------

create or replace function public.dashboard_compliance_for_caller()
returns table (domain_id uuid, month date, due_count int, on_time_count int)
language sql stable security definer set search_path = ''
as $fn$
  select d.domain_id, d.month, d.due_count, d.on_time_count
  from public.dashboard_compliance_monthly d
  where public.is_active_user()
    and public.has_permission_in_domain('occurrence.read', d.domain_id)
$fn$;

create or replace function public.dashboard_upcoming_for_caller()
returns table (domain_id uuid, week_start date, total int, not_started int)
language sql stable security definer set search_path = ''
as $fn$
  select d.domain_id, d.week_start, d.total, d.not_started
  from public.dashboard_upcoming_load d
  where public.is_active_user()
    and public.has_permission_in_domain('occurrence.read', d.domain_id)
$fn$;

create or replace function public.dashboard_late_reasons_for_caller()
returns table (domain_id uuid, late_reason_code public.late_reason_code, total int)
language sql stable security definer set search_path = ''
as $fn$
  select d.domain_id, d.late_reason_code, d.total
  from public.dashboard_late_reasons d
  where public.is_active_user()
    and public.has_permission_in_domain('occurrence.read', d.domain_id)
$fn$;

create or replace function public.dashboard_workload_for_caller()
returns table (
  domain_id uuid, department_id uuid, owner_id uuid, open_total int, late_total int)
language sql stable security definer set search_path = ''
as $fn$
  select d.domain_id, d.department_id, d.owner_id, d.open_total, d.late_total
  from public.dashboard_workload d
  where public.is_active_user()
    and public.has_permission_in_domain('occurrence.read', d.domain_id)
$fn$;

create or replace function public.dashboard_health_for_caller()
returns table (
  domain_id uuid, pending_validation int, pending_avg_days numeric,
  documents_required int, documents_provided int)
language sql stable security definer set search_path = ''
as $fn$
  select d.domain_id, d.pending_validation, d.pending_avg_days,
         d.documents_required, d.documents_provided
  from public.dashboard_health d
  where public.is_active_user()
    and public.has_permission_in_domain('occurrence.read', d.domain_id)
$fn$;

comment on function public.dashboard_compliance_for_caller() is
  '⚠️ SECURITY DEFINER parce que la matview sous-jacente n''est accessible à '
  'personne. Le contrôle de domaine est réappliqué ICI, explicitement : c''est la '
  'seule barrière, il n''y en a pas d''autre en dessous. Les quatre autres '
  'accesseurs du tableau de bord suivent la même règle, mot pour mot.';

do $$
declare fn text;
begin
  foreach fn in array array[
    'dashboard_compliance_for_caller', 'dashboard_upcoming_for_caller',
    'dashboard_late_reasons_for_caller', 'dashboard_workload_for_caller',
    'dashboard_health_for_caller']
  loop
    execute format('revoke execute on function public.%I() from public, anon', fn);
    execute format('grant execute on function public.%I() to authenticated', fn);
  end loop;
end;
$$;

-- -----------------------------------------------------------------------------
-- Rafraîchissement
-- -----------------------------------------------------------------------------

create or replace function public.refresh_dashboard_views()
returns void
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  view_name text;
begin
  foreach view_name in array array[
    'dashboard_compliance_monthly', 'dashboard_upcoming_load',
    'dashboard_late_reasons', 'dashboard_workload', 'dashboard_health']
  loop
    begin
      -- CONCURRENTLY : le tableau de bord continue d'être lu pendant le calcul.
      execute format('refresh materialized view concurrently public.%I', view_name);
    exception
      when others then
        -- Premier rafraîchissement : la forme concurrente exige une vue déjà
        -- peuplée. On retombe sur la forme bloquante plutôt que de laisser les
        -- agrégats figés indéfiniment.
        execute format('refresh materialized view public.%I', view_name);
    end;
  end loop;
end;
$fn$;

comment on function public.refresh_dashboard_views() is
  'Rafraîchit les cinq agrégats du tableau de bord. Planifiée toutes les 15 '
  'minutes. Conséquence assumée : les chiffres affichés ont au plus un quart '
  'd''heure — sans portée sur une granularité journalière, et c''est le prix de '
  'l''objectif « aucun calcul lourd à la demande ».';

revoke execute on function public.refresh_dashboard_views() from public, anon, authenticated;

do $$
begin
  create extension if not exists pg_cron;
  perform cron.unschedule('conformia-dashboard')
  where exists (select 1 from cron.job where jobname = 'conformia-dashboard');
  perform cron.schedule(
    'conformia-dashboard', '*/15 * * * *', 'select public.refresh_dashboard_views()');
exception
  when others then
    raise notice 'pg_cron indisponible (%). Rafraîchir refresh_dashboard_views() '
      'par un ordonnanceur externe.', sqlerrm;
end;
$$;

-- =============================================================================
-- 9. BANDEAU D'ALERTES
-- =============================================================================

/*
 * ⚠️ ÉCRITE EN PLPGSQL, ET NON EN SQL DÉCLARATIF, POUR UNE RAISON MESURÉE.
 *
 * La première version filtrait chaque branche par `can_see_occurrence(oc.id)`.
 * Fonctionnellement juste — c'est la copie fidèle du cloisonnement — mais
 * ruineux : la fonction rouvre `obligation_occurrences` pour CHAQUE ligne
 * examinée. Chronométré sur 50 000 dossiers : 2 479 ms pour le seul bandeau,
 * contre un budget de 800 ms pour la page entière.
 *
 * Le cloisonnement n'est pas relâché, il est REFORMULÉ : les domaines
 * accessibles sont calculés UNE fois, puis comparés en mémoire. Les trois
 * termes — permission de domaine, propriétaire, validateur — sont exactement
 * ceux de `can_see_occurrence`, et le test d'intégration compare toujours les
 * deux.
 *
 * ⚠️ Le bandeau ne vient PAS d'une vue matérialisée, contrairement à tout le
 * reste du tableau de bord : une alerte vieille d'un quart d'heure n'est pas une
 * alerte. Il interroge donc les tables vives, et c'est pour cela que son coût
 * devait être mesuré séparément.
 */
create or replace function public.dashboard_alerts()
returns table (code text, severity text, total int, detail jsonb)
language plpgsql
stable
security definer
set search_path = ''
as $fn$
declare
  me uuid := public.current_profile_id();
  allowed uuid[];
  null_domain_allowed boolean;
  today date := (now() at time zone 'Africa/Algiers')::date;
  n int;
begin
  if not public.is_active_user() then
    return;
  end if;

  select coalesce(array_agg(d.id), array[]::uuid[]) into allowed
  from public.domains d
  where public.has_permission_in_domain('occurrence.read', d.id);

  -- Une obligation sans domaine reste possible : son accès se décide à part.
  null_domain_allowed := public.has_permission_in_domain('occurrence.read', null);

  -- Dossiers CRITICAL en retard.
  select count(*)::int into n
  from public.obligation_occurrences oc
  join public.obligation_types ot on ot.id = oc.obligation_type_id
  where oc.deleted_at is null
    and ot.criticality = 'CRITICAL'
    and oc.legal_due_date < today
    and not (oc.status = any (public.overdue_exempt_statuses()))
    and (ot.domain_id = any (allowed)
         or (ot.domain_id is null and null_domain_allowed)
         or oc.owner_id = me or oc.validator_id = me);
  if n > 0 then
    code := 'CRITICAL_OVERDUE'; severity := 'CRITICAL'; total := n; detail := '{}'::jsonb;
    return next;
  end if;

  -- Échéance interne à moins de 48 h, et pas même commencée.
  select count(*)::int into n
  from public.obligation_occurrences oc
  join public.obligation_types ot on ot.id = oc.obligation_type_id
  where oc.deleted_at is null
    and oc.status = 'TODO'
    and oc.internal_due_date between today and today + 2
    and (ot.domain_id = any (allowed)
         or (ot.domain_id is null and null_domain_allowed)
         or oc.owner_id = me or oc.validator_id = me);
  if n > 0 then
    code := 'IMMINENT_NOT_STARTED'; severity := 'HIGH'; total := n; detail := '{}'::jsonb;
    return next;
  end if;

  -- En attente de validation depuis plus de cinq jours.
  select count(*)::int into n
  from public.obligation_occurrences oc
  join public.obligation_types ot on ot.id = oc.obligation_type_id
  where oc.deleted_at is null
    and oc.status = 'PENDING_VALIDATION'
    and oc.submitted_for_validation_at < now() - interval '5 days'
    and (ot.domain_id = any (allowed)
         or (ot.domain_id is null and null_domain_allowed)
         or oc.owner_id = me or oc.validator_id = me);
  if n > 0 then
    code := 'VALIDATION_STALE'; severity := 'HIGH'; total := n; detail := '{}'::jsonb;
    return next;
  end if;

  -- Aucune sauvegarde réussie depuis 36 h — « aucune, jamais » comprise.
  -- Réservée à qui administre l'installation : elle ne concerne personne d'autre,
  -- et l'afficher partout la banaliserait.
  if public.has_permission('settings.manage')
     and not exists (
       select 1 from public.backup_runs b
       where b.status = 'SUCCEEDED' and b.finished_at > now() - interval '36 hours')
  then
    code := 'BACKUP_STALE'; severity := 'CRITICAL'; total := 1; detail := '{}'::jsonb;
    return next;
  end if;

  -- Divergence d'intégrité documentaire non acquittée. La vue est en
  -- security_invoker : elle ne montre que les pièces déjà visibles de l'appelant.
  select count(*)::int into n from public.document_integrity_alerts;
  if n > 0 then
    code := 'INTEGRITY_MISMATCH'; severity := 'CRITICAL'; total := n; detail := '{}'::jsonb;
    return next;
  end if;

  return;
end;
$fn$;

comment on function public.dashboard_alerts() is
  'Bandeau d''alertes, calculé sur les tables VIVES — une alerte différée de '
  'quinze minutes ne vaut rien. Chaque branche applique le cloisonnement de '
  '`can_see_occurrence`, mais reformulé pour être évalué une fois par domaine et '
  'non une fois par dossier : la forme naïve coûtait 2 479 ms sur 50 000 lignes.';

grant execute on function public.dashboard_alerts() to authenticated;

-- =============================================================================
-- 10. EXPORT D'AUDIT — journalisé, comme le reste
-- =============================================================================

create or replace function public.log_audit_export(p_filters jsonb, p_row_count int)
returns void
language plpgsql
security definer
set search_path = ''
as $fn$
begin
  if not public.has_permission('audit.read') then
    raise exception 'Export refusé : audit.read requis.' using errcode = '42501';
  end if;

  insert into public.audit_log (
    actor_id, actor_email, action, entity_table, entity_id_ref, after
  )
  values (
    auth.uid(),
    (select p.email::text from public.profiles p where p.id = auth.uid()),
    'EXPORT', 'audit_log', null,
    jsonb_build_object('filters', p_filters, 'row_count', p_row_count)
  );
end;
$fn$;

comment on function public.log_audit_export(jsonb, int) is
  '⚠️ L''export du journal est lui-même journalisé, avec ses filtres et son '
  'volume. Sans cela, le seul geste capable de faire sortir l''intégralité de la '
  'traçabilité de l''entreprise serait le seul à ne pas en laisser.';

grant execute on function public.log_audit_export(jsonb, int) to authenticated;

-- Le journal se consulte par période et par acteur : sans cet index, un filtre
-- d'écran devient un balayage complet de la partition.
create index if not exists audit_log_action_idx on public.audit_log (action, occurred_at desc);
