-- =============================================================================
-- 0013 — MOTEUR DE GÉNÉRATION DES OCCURRENCES
--
-- Trois pièces, et rien d'autre :
--
--   1. `job_runs` — le journal des exécutions. Une tâche planifiée dont on ne
--      sait pas si elle a tourné n'est pas une tâche planifiée : c'est un espoir.
--
--   2. UN VERROU CONSULTATIF. Deux exécutions simultanées du générateur ne
--      créeraient pas de doublons — la contrainte d'unicité y veille — mais
--      elles se disputeraient les mêmes lignes, doubleraient la charge et
--      rendraient les rapports illisibles. Le verrou est pris pour la durée de
--      la SESSION, et relâché explicitement.
--
--   3. LA PLANIFICATION à 02 h 00, heure d'Alger.
--      ⚠️ pg_cron raisonne en UTC. Alger est à UTC+1 SANS heure d'été : 02 h 00
--      locales valent donc 01 h 00 UTC toute l'année. Écrire « 0 2 * * * » ferait
--      tourner la tâche à 03 h 00 locales — sans conséquence visible, ce qui est
--      précisément ce qui rend l'erreur durable.
-- =============================================================================

-- =============================================================================
-- 1. JOURNAL DES EXÉCUTIONS
-- =============================================================================

create table public.job_runs (
  id bigint generated by default as identity primary key,
  job_name text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'RUNNING'
    check (status in ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'SKIPPED')),
  processed_count int not null default 0,
  error_count int not null default 0,
  details jsonb not null default '{}'::jsonb
);

comment on table public.job_runs is
  'Journal des tâches planifiées. Chaque exécution y laisse une ligne, y compris '
  'celles qui n''ont RIEN fait — un silence ne se distingue pas d''une panne. '
  'Le statut PARTIAL existe parce que le générateur poursuit après un échec '
  'unitaire : dire « réussi » masquerait les obligations non traitées, dire '
  '« échoué » masquerait les autres.';
comment on column public.job_runs.status is
  'RUNNING pendant l''exécution — une ligne restée à RUNNING signale un processus '
  'interrompu, et c''est une information. SKIPPED quand le verrou était déjà pris.';
comment on column public.job_runs.details is
  'Rapport détaillé : obligations traitées, occurrences créées, erreurs par '
  'obligation. Sert au diagnostic sans exiger la relecture des journaux serveur.';

create index job_runs_name_idx on public.job_runs (job_name, started_at desc);
-- Exécutions en cours ou en échec : la seule interrogation réellement chaude.
create index job_runs_unfinished_idx on public.job_runs (started_at desc)
  where status in ('RUNNING', 'FAILED', 'PARTIAL');

alter table public.job_runs enable row level security;
revoke insert, update, delete on public.job_runs from public, anon, authenticated;
grant select on public.job_runs to authenticated;

create policy job_runs_select on public.job_runs
  for select to authenticated
  using (public.is_active_user() and public.has_permission('settings.manage'));
comment on policy job_runs_select on public.job_runs is
  'Exploitation technique : réservé à qui administre l''installation.';

-- -----------------------------------------------------------------------------
-- Ouverture et clôture d'une exécution
-- -----------------------------------------------------------------------------

create or replace function public.start_job_run(p_job_name text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  run_id bigint;
begin
  insert into public.job_runs (job_name) values (p_job_name) returning id into run_id;
  return run_id;
end;
$fn$;

create or replace function public.finish_job_run(
  p_run_id bigint,
  p_status text,
  p_processed int,
  p_errors int,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $fn$
begin
  update public.job_runs
  set finished_at = now(),
      status = p_status,
      processed_count = p_processed,
      error_count = p_errors,
      details = coalesce(p_details, '{}'::jsonb)
  where id = p_run_id;
end;
$fn$;

comment on function public.finish_job_run(bigint, text, int, int, jsonb) is
  'Clôt une exécution. ⚠️ Doit être appelée MÊME EN CAS D''ÉCHEC : une ligne '
  'restée à RUNNING est le seul signal distinguant une tâche interrompue d''une '
  'tâche qui n''a jamais démarré.';

revoke execute on function public.start_job_run(text) from public, anon, authenticated;
revoke execute on function public.finish_job_run(bigint, text, int, int, jsonb)
  from public, anon, authenticated;

-- =============================================================================
-- 2. VERROU CONSULTATIF
-- =============================================================================

/*
 * Clé du verrou : dérivée du nom de la tâche par hachage. `hashtext` rend un
 * int4, exactement ce qu'attend `pg_try_advisory_lock(int)`.
 *
 * ⚠️ VERROU DE SESSION, pas de transaction. Le générateur travaille en
 * plusieurs transactions — une par obligation, pour qu'un échec unitaire
 * n'annule pas le lot. Un `pg_advisory_xact_lock` serait relâché à la première
 * validation et n'empêcherait plus rien.
 *
 * Conséquence à connaître : le verrou survit tant que la CONNEXION vit. Un
 * processus tué sans relâcher laisse le verrou pris jusqu'à la fermeture de sa
 * connexion — que PostgreSQL provoque à la coupure du socket. C'est le
 * comportement voulu : mieux vaut une exécution sautée qu'une exécution double.
 */
create or replace function public.try_lock_job(p_job_name text)
returns boolean
language sql
security definer
set search_path = ''
as $fn$
  select pg_catalog.pg_try_advisory_lock(pg_catalog.hashtext(p_job_name));
$fn$;

create or replace function public.unlock_job(p_job_name text)
returns boolean
language sql
security definer
set search_path = ''
as $fn$
  select pg_catalog.pg_advisory_unlock(pg_catalog.hashtext(p_job_name));
$fn$;

comment on function public.try_lock_job(text) is
  'Prend le verrou d''exécution, ou rend false s''il est déjà tenu. NE BLOQUE '
  'JAMAIS : une tâche planifiée qui attend son tour s''empile, et deux heures '
  'plus tard on a douze processus en file au lieu d''une exécution sautée.';

revoke execute on function public.try_lock_job(text) from public, anon, authenticated;
revoke execute on function public.unlock_job(text) from public, anon, authenticated;

-- =============================================================================
-- 3. CRÉATION D'UNE OCCURRENCE — idempotente par construction
-- =============================================================================

/*
 * ⚠️ IDEMPOTENCE. La contrainte `obligation_occurrences_period_key`
 * (entity_id, obligation_type_id, period_key) existe depuis 0001. Le `on
 * conflict do nothing` s'appuie dessus : une période déjà générée n'est JAMAIS
 * régénérée, quel que soit son statut — y compris si elle a été traitée,
 * validée, déposée, ou déclarée sans objet.
 *
 * C'est la garantie qui rend le moteur rejouable : deux exécutions consécutives
 * produisent exactement le même état. Sans elle, une seconde passe écraserait le
 * travail déjà fait, ce qui serait pire que de ne rien générer du tout.
 */
create or replace function public.create_occurrence_if_absent(
  p_obligation_type_id uuid,
  p_period_key text,
  p_period_start date,
  p_period_end date,
  p_legal_due_date date,
  p_internal_due_date date,
  p_status public.occurrence_status default 'TODO'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  new_id uuid;
  obligation record;
begin
  select ot.id, ot.entity_id, ot.default_owner_id, ot.default_validator_id
    into obligation
  from public.obligation_types ot
  where ot.id = p_obligation_type_id and ot.deleted_at is null;

  if obligation.id is null then
    raise exception 'Obligation introuvable : %.', p_obligation_type_id using errcode = '22023';
  end if;

  insert into public.obligation_occurrences (
    entity_id, obligation_type_id, period_key, period_start, period_end,
    legal_due_date, internal_due_date, status, owner_id, validator_id
  )
  values (
    obligation.entity_id, p_obligation_type_id, p_period_key, p_period_start, p_period_end,
    p_legal_due_date, p_internal_due_date, p_status,
    obligation.default_owner_id, obligation.default_validator_id
  )
  on conflict (entity_id, obligation_type_id, period_key) do nothing
  returning id into new_id;

  -- `new_id` est NULL quand la période existait déjà : ce n'est pas une erreur,
  -- c'est le comportement recherché. L'appelant compte les créations réelles.
  if new_id is null then
    return null;
  end if;

  -- Liste de contrôle, recopiée du référentiel AU MOMENT de la création. Une
  -- pièce ajoutée au référentiel plus tard ne remonte pas dans les dossiers
  -- déjà ouverts : leur composition est celle qui était exigée à leur ouverture.
  insert into public.occurrence_checklist_items
    (occurrence_id, label, is_mandatory, document_kind, order_index)
  select new_id, rd.label, rd.is_mandatory, rd.document_kind, rd.order_index
  from public.obligation_required_documents rd
  where rd.obligation_type_id = p_obligation_type_id;

  return new_id;
end;
$fn$;

comment on function public.create_occurrence_if_absent is
  'Crée une occurrence SI la période n''existe pas déjà, avec sa liste de '
  'contrôle et ses affectations par défaut. Rend NULL quand la période existait — '
  'un silence délibéré, pas une erreur. C''est cette fonction qui rend le '
  'générateur rejouable.';

revoke execute on function public.create_occurrence_if_absent(
  uuid, text, date, date, date, date, public.occurrence_status)
  from public, anon, authenticated;

-- =============================================================================
-- 4. PLANIFICATION
-- =============================================================================

do $$
begin
  create extension if not exists pg_cron;

  perform cron.unschedule('conformia-generate-occurrences')
  where exists (select 1 from cron.job where jobname = 'conformia-generate-occurrences');

  /*
   * ⚠️ 01 h 00 UTC = 02 h 00 À ALGER. pg_cron planifie en UTC, et l'Algérie est
   * à UTC+1 toute l'année — pas d'heure d'été depuis 1981. Écrire « 0 2 * * * »
   * ferait tourner la tâche à 03 h 00 locales : sans conséquence visible, donc
   * jamais corrigé.
   */
  perform cron.schedule(
    'conformia-generate-occurrences',
    '0 1 * * *',
    $job$select net.http_post(
      url := current_setting('app.generate_occurrences_url', true),
      headers := jsonb_build_object('Content-Type', 'application/json')
    )$job$);
exception
  when others then
    raise notice 'pg_cron/pg_net indisponible (%). Déclencher la génération par '
      'un ordonnanceur externe sur POST /api/cron/generate.', sqlerrm;
end;
$$;
