-- =============================================================================
-- 0017 — LIMITATION DE DÉBIT DES ÉCRITURES
--
-- ⚠️ CE QUI EXISTAIT NE COUVRAIT QUE LA CONNEXION.
--
-- `is_auth_throttled` (0004) protège le formulaire de connexion contre les
-- essais en série. Tout le reste — dépôt de pièce, transition d'état, export,
-- commentaire, création d'obligation — n'avait AUCUNE borne : une boucle, un
-- script, un onglet resté ouvert sur une action qui se relance pouvaient
-- produire des milliers d'écritures, chacune parfaitement légitime prise
-- isolément, et chacune laissant sa ligne d'audit.
--
-- ⚠️ LE COMPTEUR VIT EN BASE, PAS EN MÉMOIRE.
--
-- Un compteur en mémoire de processus est remis à zéro à chaque déploiement et
-- ne voit rien de ce qui passe par les autres instances. Sur un hébergement qui
-- démarre plusieurs conteneurs — le cas de toute mise à l'échelle — il ne limite
-- rien du tout tout en donnant l'impression du contraire. La table le rend
-- partagé, durable, et observable.
-- =============================================================================

create table public.rate_limit_hits (
  id bigint generated by default as identity primary key,
  -- Qui : l'utilisateur s'il y en a un, sinon l'adresse d'origine.
  subject text not null,
  -- Quoi : la famille d'actions limitée (« mutation », « export », …).
  bucket text not null,
  occurred_at timestamptz not null default now()
);

comment on table public.rate_limit_hits is
  'Empreintes des écritures, pour la limitation de débit. Purgée au fil de l''eau : '
  'seule la fenêtre courante a une valeur, l''historique est déjà dans audit_log.';

-- La lecture porte toujours sur (sujet, seau, fenêtre récente) : l'index suit.
create index rate_limit_hits_window_idx
  on public.rate_limit_hits (subject, bucket, occurred_at desc);

alter table public.rate_limit_hits enable row level security;

/*
 * ⚠️ AUCUNE POLICY PERMISSIVE, ET C'EST VOULU. La table n'est jamais lue ni
 * écrite directement : tout passe par `consume_rate_limit()`, SECURITY DEFINER.
 * RLS activée sans policy = zéro ligne visible, zéro écriture possible pour
 * `authenticated`. C'est la posture la plus stricte que le modèle permette, et
 * elle est ici exactement adaptée.
 */
revoke all on public.rate_limit_hits from public, anon, authenticated;

comment on column public.rate_limit_hits.subject is
  'Identifiant de l''utilisateur, ou « ip:… » quand la requête est anonyme. Jamais '
  'une adresse électronique : ce serait une donnée personnelle dans une table de comptage.';

-- -----------------------------------------------------------------------------
-- Consommation d'un jeton
--
-- Rend `{allowed, remaining, retry_after_seconds}`. L'appelant décide quoi en
-- faire : le middleware refuse en 429, un job pourrait se contenter d'attendre.
--
-- ⚠️ L'ENREGISTREMENT A LIEU MÊME QUAND L'APPEL EST REFUSÉ. C'est délibéré : une
-- salve qui continue de frapper doit continuer de compter, sinon la fenêtre se
-- vide pendant l'attaque et le premier essai suivant repasse.
-- -----------------------------------------------------------------------------

create or replace function public.consume_rate_limit(
  p_subject text,
  p_bucket text,
  p_limit int,
  p_window_seconds int
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  window_start timestamptz := now() - make_interval(secs => p_window_seconds);
  used int;
  oldest timestamptz;
begin
  if p_subject is null or pg_catalog.btrim(p_subject) = '' then
    -- Sans sujet, il n'y a rien à limiter : refuser ici bloquerait des appels
    -- légitimes hors session (sonde, tâche) sans protéger personne.
    return jsonb_build_object('allowed', true, 'remaining', p_limit, 'retry_after_seconds', 0);
  end if;

  insert into public.rate_limit_hits (subject, bucket)
  values (p_subject, p_bucket);

  select count(*), min(occurred_at)
    into used, oldest
  from public.rate_limit_hits
  where subject = p_subject
    and bucket = p_bucket
    and occurred_at >= window_start;

  /*
   * Purge opportuniste : une ligne sur cinquante déclenche le nettoyage de la
   * table au-delà d'une heure. Une tâche planifiée dédiée serait un travail de
   * plus à surveiller pour une table qui ne dépasse jamais quelques milliers de
   * lignes ; la faire au fil de l'eau coûte moins et ne peut pas s'arrêter.
   */
  if used % 50 = 0 then
    delete from public.rate_limit_hits where occurred_at < now() - interval '1 hour';
  end if;

  return jsonb_build_object(
    'allowed', used <= p_limit,
    'remaining', greatest(p_limit - used, 0),
    'retry_after_seconds',
      case
        when used <= p_limit then 0
        else greatest(
          ceil(extract(epoch from (oldest + make_interval(secs => p_window_seconds)) - now()))::int,
          1)
      end
  );
end;
$$;

comment on function public.consume_rate_limit(text, text, int, int) is
  'Consomme un jeton de débit et rend le verdict. L''appel est COMPTÉ même lorsqu''il '
  'est refusé : sans cela, une salve continue viderait la fenêtre pendant l''attaque. '
  'Rend toujours « autorisé » sans sujet — un appel hors session n''est pas limitable, '
  'et le refuser bloquerait des tâches légitimes sans gêner personne d''autre.';

revoke execute on function public.consume_rate_limit(text, text, int, int) from public;
grant execute on function public.consume_rate_limit(text, text, int, int)
  to anon, authenticated, service_role;
